### ISSUE TITLE
same Error comes POST Method how to rectify the error help us..........

### ISSUE THREAD

**Issue by anitakinisha** [palantir/conjure-java-runtime#1021]
same Error comes POST Method how to rectify the error help us..........

` @FormUrlEncoded
    @POST
    Call Login(@Field("method") String method,@Field("email") String username, @Field("password") String password);
`
My Error is:

> java.lang.IllegalArgumentException: Unable to create call adapter for interface retrofit2.Call
        for method Interface.Login

_Originally posted by @143Deepu in https://github.com/palantir/conjure-java-runtime/issues/561#issuecomment-387657442_

**Comment by 143Deepu** [comment]
Hai Anitakinisha,

                      It's working code  please recheck a hole code once


*Manideep Aravapalli*

**Comment by iamdanfox** [comment]
Is this issue related to conjure-java-runtime? Perhaps https://github.com/square/retrofit would be a better place?
