### ISSUE TITLE
Provide an option to disable http2 in client

### ISSUE THREAD

**Issue by kmblake** [palantir/conjure-java-runtime#1058]
It's possible to [create an okhttp3 client that only supports HTTP/1.1](https://stackoverflow.com/questions/41925501/java-okhttp3-only-use-http-1-1-or-http-2), but this configuration is is not exposed at the JaxRsClient level. Can we make the JaxRsClient similarly configurable to disable HTTP/2?

**Comment by iamdanfox** [comment]
From the linked PR:

> Did some more debugging, and it turned out that the client and server were unable to agree on a cipher for HTTP/2. Enabling GCM cipher suites fixed it, so this change is no longer needed from my end.
