### ISSUE TITLE
Support multiple URI's for the Retrofit client factory

### ISSUE THREAD

**Issue by eshlin** [palantir/conjure-java-runtime#107]
For certain scenarios, a Retrofit client might be required, rather than the recommended Feign client, such as when communicating with streaming endpoints. It'd be great to have a version of RetrofitClientFactory.createProxy that supports multiple URI's, similar to the FeignClientFactory.createProxy method.

**Comment by uschi2000** [comment]
@ellisjoe

**Comment by eshlin** [comment]
closing this out, since this was addressed in #212
