### ISSUE TITLE
add `isServiceEnabled` for service discovery

### ISSUE THREAD

**Issue by sixinli** [palantir/conjure-java-runtime#110]
can we have `isServiceEnabled` = there's config for the service and uris is not empty?

**Comment by uschi2000** [comment]
sure. side-note: does it even make sense to define a service with zero uris? could easily enforce this.

**Comment by pnepywoda** [comment]
what's the use-case for this?

**Comment by sixinli** [comment]
to check if a service is enable conveniently? i have services that might have empty uris, in which is actually not enabled. i want to easily find out if a service is enable or not then do different things based on that

**Comment by pnepywoda** [comment]
Lol....I know......but why?

**Comment by sixinli** [comment]
on which part? why do i want to have different behavior? or why is there service with empty uri?
