### ISSUE TITLE
Allow HostnameVerifier to be set for clients

### ISSUE THREAD

**Issue by nmiyake** [palantir/conjure-java-runtime#122]
Currently, the `CLIENT_SUPPLIER` objects in `FeignClientFactory` are defined as `Function<Optional<SSLSocketFactory>, Client>`. It would be helpful to have the ability to specify the `HostnameVerifier` in addition to the factory (this is the other constructor parameter for `Client.Default()` in Feign, and is supported by `OkHttp` as well).

Concretely:
- Create new `HttpClientParams` class that contains `Optional<SSLSocketFactory> sslSocketFactory` and `Optional<HostnameVerifier> hostnameVerifier`
- Modify suppliers as follows:

```
    private static final Function<HttpClientParams, Client> OKHTTP_CLIENT_SUPPLIER =
            new Function<HttpClientParams, Client>() {
                @Override
                public Client apply(HttpClientParams params) {
                    com.squareup.okhttp.OkHttpClient client = new com.squareup.okhttp.OkHttpClient();
                    client.setSslSocketFactory(params.sslSocketFactory.orNull());
                    client.setHostnameVerifier(params.hostnameVerifier.orNull());
                    return new OkHttpClient(client);
                }
            };

    private static final Function<HttpClientParams, Client> DEFAULT_CLIENT_SUPPLIER =
            new Function<HttpClientParams, Client>() {
                @Override
                public Client apply(HttpClientParams params) {
                    return new Client.Default(params.sslSocketFactory.orNull(), params.hostnameVerifier.orNull());
                }
            };
```
- Propagate changes down-stream (preserve current APIs to default to `Optional.absent()` for `HostnameVerifier`, but add new APIs that accept `HttpClientParams`).

---

Motivation:

With Docker networking, internal container ports are mapped to "localhost" -- in order to connect to the container `axiom.skylab.dev:3000` from the host machine, the host machine establishes a connection to `localhost:3000`. However, if the container is a server that provides a certificate, we'll encounter a hostname mismatch -- the certificate we received is signed for "axiom.skylab.dev", but the hostname we connected to is `localhost`, so the hostname verification fails.

Being able to set the verifier would allow working around this in test environments -- it would be possible to provide a verifier that would work around this (allow the proper matches or skip entirely).

I think this is reasonable given that `Feign` views `HostnameVerifier` at the same level as `SSLSocketFactory` for their clients. It is possible to work around this (client can bypass `FeignClientFactory` and just create the proxy themselves), but wanted to open for discussion.

**Comment by nmiyake** [comment]
@markelliot @uschi2000

**Comment by nmiyake** [comment]
Note that implementation above would be a backcompat-break since we do expose `Function<Optional<SSLSocketFactory>, Client>` as a public field. However, migration should be pretty straight-forward, and if we do this change I think it'd be cleaner to eat the break over putting in a bunch of code to support compatibility for both (wouldn't be hard to do, but would add cruft)

**Comment by markelliot** [comment]
I'm starting to wonder if we should switch to an service discovery model instead of asking consumers to inject all these parameters. Are there places where we want to parameterize client instantiation differently  within the same application?

**Comment by nmiyake** [comment]
What would a discovery model look like here? Producer would advertise parameters required by client to connect and they would establish connection using that? Although my use is probably atypical, I use http-remoting in a lot of my library unit tests to connect to services I want to test over http (I use remoting because it provides niceness for configuring object and exception mappers, failover etc.), so heavy-weight discovery wouldn't solve my particular use cases (although mine are certainly not the most important)

**Comment by markelliot** [comment]
I imagine we'd have multiple implementations of something like:

```
interface ClientSupplier {
    Client get()
}
```

Maybe that's unrealistic because there's no way to plumb the SSL stuff?

**Comment by nmiyake** [comment]
Worked around this so no longer as urgent. Will keep issue open since I may tackle later, but on the back-burner for me for now.

**Comment by markelliot** [comment]
still planning to do something here, @nmiyake?

**Comment by uschi2000** [comment]
I am not a big fan of this. For the Docker case specifically, I prefer tweaking the DNS setup to map *.palantir.dev --> 127.0.0.1. Let me know if you still need this, Nick, and we can re-consider.
