### ISSUE TITLE
Maven URL appears to have changed

### ISSUE THREAD

**Issue by chris05atm** [palantir/conjure-java-runtime#1345]
## What happened?

Documentation states that libraries are published to JCenter. It appears Palantir now publishes to http://palantir.bintray.com/releases.

## What did you want to happen?

Correct the documentation if I'm right.

**Comment by iamdanfox** [comment]
I think all our open-source code is published to bintray by default, because that can be done with automation, whereas getting stuff onto jcenter is a manual process. Let me kick off the ticket for that process.

**Comment by iamdanfox** [comment]
@aggie05engineer apparently some syncing was stuck, but everything should now be present in jcenter again! https://jcenter.bintray.com/com/palantir/conjure/java/runtime/
