### ISSUE TITLE
Allow request interceptors to be set

### ISSUE THREAD

**Issue by a-k-g** [palantir/conjure-java-runtime#136]
In our project, we would like to send the version as part of the request headers while talking among various internal services. Presently this blocks us from using the factories provided by `http-remoting` library. We're having to do something custom like -

```
public static <T> T create(Class<T> serviceClass,
                               ProductVersion version,
                               SSLSocketFactory socketFactory,
                               URL serviceBaseUrl) {
        OkHttpClient okHttpClient = new OkHttpClient();
        okHttpClient.setSocketFactory(socketFactory);
        Client client = new feign.okhttp.OkHttpClient(okHttpClient);
        return Feign.builder()
                    .contract(new JAXRSContract())
                    .encoder(new JacksonEncoder(mapper))
                    .decoder(new JacksonDecoder(mapper))
                    .requestInterceptor(request -> request.header(VersionHeader.VERSION_HEADER, version.toJson()))
                    .client(client)
                    .target(serviceClass, serviceBaseUrl.toString());
    }
```

**Comment by markelliot** [comment]
What are you doing with the header on the other side?

**Comment by uschi2000** [comment]
Wouldn't it be more interesting to send the server version so that clients
can understand which server they talk to and multiplex accordingly?
  R.

**Comment by a-k-g** [comment]
We intend to use the version to make sure that compatible versions of services talk to each other. I don't have a strong opinion about who should be sending the header.

At the moment, we don't intend to multiplex, so just helpful log messages (on both server and client) in case of version mismatches would be enough - and for that we need to add the request interceptor.

**Comment by markelliot** [comment]
2 things:
1. You could send the header explicitly with each invocation (this seems lame)
2. We added a User Agent string option in 0.12. 

Besides that, I don't think we want to keep producing factory methods that just wrap Feign, and per Rob, if we were to build a version header into the system we'd do so on the return side.

**Comment by a-k-g** [comment]
Thanks! Option 2 seems quite reasonable for our use-case
