### ISSUE TITLE
TRACE log requests on client and server side

### ISSUE THREAD

**Issue by ash211** [palantir/conjure-java-runtime#153]
Request send on client side covered by https://github.com/palantir/http-remoting/tree/jellis/logRequests
Need request receive on server side as well

cc @ellisjoe

**Comment by markelliot** [comment]
Don't you get server side logs of received traffic from a standard request log?

**Comment by ash211** [comment]
I was debugging an issue that required looking at HTTP headers (including `Authorization`) and those aren't logged in the standard request log.

**Comment by markelliot** [comment]
I'm not sure we should ever enable logging of the Authorization header, though.

**Comment by uschi2000** [comment]
Yep, we can log the (unverified) user name, but shouldn't log the token
itself.

**Comment by ash211** [comment]
How would you suggest debugging an issue with HTTP headers if we don't have logging?  This would be in TRACE logs, not enabled by default.

Outbound request from one service looks like this:

```
2016-07-01 07:54:06,653 TRACE com.palantir.remoting.http.RequestLoggerInterceptor - Request: GET /catalog/datasets/ri.foundry.main.dataset.6bfe6f8f-3ea2-4a78-a003-b922cef97876/transactions/ri.foundry.main
.transaction.00000000-0a97-059b-b379-83b48fdb44ac/files?logicalPath=spark-ri.foundry.main.transaction.00000000-0a97-059b-b379-83b48fdb44ac HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyREDACTED
```

Inbound request on other side looks like this:

```
TRACE [2016-07-01 07:54:06,767] com.palantir.foundry.catalog.RequestLoggingFilter: Request: (GET /catalog/api/catalog/datasets/ri.foundry.main.dataset.6bfe6f8f-3ea2-4a78-a003-b922cef97876/transactions/ri.foundry.main.transaction.00000000-0a97-059b-b379-83b48fdb44ac/files?logicalPath=spark-ri.foundry.main.transaction.00000000-0a97-059b-b379-83b48fdb44ac?logicalPath=spark-ri.foundry.main.transaction.00000000-0a97-059b-b379-83b48fdb44ac)@547737314 org.eclipse.jetty.server.Request@20a5cee2
TRACE [2016-07-01 07:54:06,768] com.palantir.foundry.catalog.RequestLoggingFilter: Header - Connection: close
TRACE [2016-07-01 07:54:06,768] com.palantir.foundry.catalog.RequestLoggingFilter: Header - User-Agent: okhttp/2.7.5
TRACE [2016-07-01 07:54:06,768] com.palantir.foundry.catalog.RequestLoggingFilter: Header - Host: REDACTED.com
TRACE [2016-07-01 07:54:06,768] com.palantir.foundry.catalog.RequestLoggingFilter: Header - Accept-Encoding: gzip
TRACE [2016-07-01 07:54:06,768] com.palantir.foundry.catalog.RequestLoggingFilter: Header - Accept: application/json
TRACE [2016-07-01 07:54:06,768] com.palantir.foundry.catalog.RequestLoggingFilter: URL: https://REDACTED.com/catalog/api/catalog/datasets/ri.foundry.main.dataset.6bfe6f8f-3ea2-4a78-a003-b922cef97876/transactions/ri.foundry.main.transaction.00000000-0a97-059b-b379-83b48fdb44ac/files
```

Note that the `Authorization` header is no longer there, and the destination URL now has two query parameters `?logicalPath=...`

For this particular issue I suspect classpath problems on the sending side, but I never would've been able to debug this class of issue if I hadn't had TRACE logging of full request in both send and receive sides of the remoting call.

**Comment by markelliot** [comment]
I think it's a security concern for administrators to be able to enable logging and extract headers; we can modify services to print more useful errors for bad headers (and any other kind of bad input) to aid with debugging, but I don't think this is something we can build into this library.

**Comment by ash211** [comment]
Root cause cause of the above was an incorrectly-configured nginx proxy and requests going to http instead of https.  That ended up being discoverable without adding additional logging for the bearer token, so this ended up not being a supporting example of why logging HTTP parameters (like BearerToken) at the TRACE level would be good.

Therefore, closing
