### ISSUE TITLE
http-servers -> jaxrs-servers?

### ISSUE THREAD

**Issue by markelliot** [palantir/conjure-java-runtime#203]

**Comment by uschi2000** [comment]
or maybe even dropwizard-servers?

**Comment by markelliot** [comment]
Is it Dropwizard specific?

**Comment by uschi2000** [comment]
Yes.
https://github.com/palantir/http-remoting/blob/develop/http-servers/src/main/java/com/palantir/remoting1/servers/DropwizardServers.java#L32

**Comment by markelliot** [comment]
Interesting. The only thing we seem to require Dropwizard for here is that we're registering both servlet filters and jersey resources. Not looking super closely, but I think we might be able to remove the Dropwizard dependency.

**Comment by uschi2000** [comment]
It's not super-obvious how to remote the dependency on dropwizard-jetty, I
think. Haven't dug very deep though.

**Comment by markelliot** [comment]
I missed that, what are we using?

Also, not a big deal to keep a DW dependency

**Comment by uschi2000** [comment]
The dropwirzard jetty filter API wraps jetty I think. We only use this for
brave at the moment.

**Comment by uschi2000** [comment]
closed by #204
