### ISSUE TITLE
Retrofit2Client and capturing raw requests/responses

### ISSUE THREAD

**Issue by elektron9** [palantir/conjure-java-runtime#213]
I often use vanilla Retrofit's capabilities to intercept and log Requests and Responses for debugging purposes. However, the `Retrofit2ClientBuilder.build()` method does not allow me to add an OkHttp Interceptor to my client before constructing it.

It would be very handy if either (a) this constructor could allow me to add an Interceptor to my client (see http://stackoverflow.com/a/33256827/866021) or (b) if it could somehow log raw requests and responses at the `DEBUG` level for testing.

**Comment by uschi2000** [comment]
Do you ever need to mutate the request/response, or would an observer suffice?

**Comment by elektron9** [comment]
@uschi2000: an observer would suffice for my purposes - or even just a `DEBUG` logging statement which logs the raw request/response for me. Thanks!

**Comment by uschi2000** [comment]
OK, cool, that's easy enough. Do you want to give it a shot?

**Comment by elektron9** [comment]
@uschi2000: certainly. I'll send a PR your way soon!

**Comment by ash211** [comment]
This sounds like a repeat request for better debuggability of the requests going across the wire that I filed here: https://github.com/palantir/http-remoting/issues/153

@uschi2000 are we comfortable making the debug logging possible via the an Interceptor but not logging that data in the framework itself?

**Comment by uschi2000** [comment]
would you like to see hard-wired trace-level logging, @ash211 ?

**Comment by ash211** [comment]
In the linked ticket I would've found it useful to be able to configure a log4j config file and see request tracing.  It sounds like @elektron9 's reason for wanting an Interceptor is to trace log requests as well.

**Comment by elektron9** [comment]
@ash211, @uschi2000 - just checking: if users could configure an entire Interceptor, would they be able to circumvent any of the other tools in this library? Interceptors do add a high degree of flexibility along a request chain.

**Comment by uschi2000** [comment]
yep, and that's exactly why I'd like to outlaw them.

**Comment by elektron9** [comment]
@uschi2000: Please see https://github.com/palantir/http-remoting/pull/214 for the PR, thanks!

**Comment by uschi2000** [comment]
cheers! commenting on the PR.

**Comment by markelliot** [comment]
we closed #214 due to security concerns, following suit here
