### ISSUE TITLE
errorInstanceId not logged with Dropwizard

### ISSUE THREAD

**Issue by michal-draftwise** [palantir/conjure-java-runtime#2179]
## What happened?

When there is an uncaught exception thrown in my Dropwizard application the response contains the following:

```
{
  "errorCode": "<ERROR CODE>",
  "errorName": "<ERROR NAME>",
  "errorInstanceId": "<ERROR UUID>",
  "parameters": {
     [...]
  }
}
```

However, that **errorInstanceId** is never logged so it is not possible to easily tie that response to the corresponding exception.

## What did you want to happen?

I want **errorInstanceId** to be displayed somewhere in the log of the corresponding exception in my Dropwizard application.

**Comment by carterkozak** [comment]
Thanks for the report, @michal-draftwise! We have an internal logging implementation which doesn't rely on slf4j parameter interpolation, however in most of our OSS libraries we try to ensure arguments are interpolated to avoid problems like this one -- it looks like our exception handlers do not have `{}`. I'll fix them up :-)
