### ISSUE TITLE
The source jars for jaxrs-clients (and maybe others) don't exist in artifactory

### ISSUE THREAD

**Issue by justinuang** [palantir/conjure-java-runtime#218]
Doesn't have a source jar.

**Comment by uschi2000** [comment]
https://github.com/palantir/http-remoting/pull/217

**Comment by markwongsk** [comment]
Is it possible to read the shaded sources? For example, I want to break in SynchronousMethodHandler to inspect the request right before it gets sent, but in Eclipse I currently just get a bytecode dump of the file. FWIW I bumped to 1.0.3 and I still don't see any sources.

**Comment by markelliot** [comment]
per @uschi2000 fixed in #217
