### ISSUE TITLE
Include interface that config DropwizardServers#configure can use to get stacktracePropagation setting

### ISSUE THREAD

**Issue by jared2501** [palantir/conjure-java-runtime#228]
To make this:

```
DropwizardServers.configure(env, config, USER_AGENT, true);
```

into this

```
DropwizardServers.configure(env, config, USER_AGENT);
```

And now everybody doesn't have to choose a different config name to put this on

**Comment by markelliot** [comment]
I think generally we don't want users to enable stacktrace propagation.

**Comment by jared2501** [comment]
For integration testing it's quite nice

**Comment by uschi2000** [comment]
I don't quite understand what the ask is here, sorry

**Comment by jared2501** [comment]
At the moment its up to every product to come up with a different name in their configuration.yml for what they call the ability to turn on or off stack trace propagation. If you require that the user's dropwizard config extends an interface then you control what the user has to call this so its the same across everything.

**Comment by markelliot** [comment]
We do not want anyone to make this configurable – I'm tempted for us to force it to false at this point, actually.

**Comment by jared2501** [comment]
It makes circle debugging sad :( but sure
