### ISSUE TITLE
.pem file based trust store

### ISSUE THREAD

**Issue by markelliot** [palantir/conjure-java-runtime#23]
Support .pem files on disk for use with a trust store. Ideally support dynamic loading of new certificates without restart. 

When keystore support is added, support defining a private key for use with a .pem file.

**Comment by nmiyake** [comment]
What do you envision this would actually look like from a config standpoint (how would a user/dev specify that they want to use a PEM file as part of their store)? Can take a look at doing this as a side/background thing if you think it would be useful.

**Comment by uschi2000** [comment]
I think the general motivation is reduce the pain of having to fiddle with
openssl commands to turn keys/certs/chains/foos/bars into Java-compatible
key stores. I haven't quite made up my mind what functionality exactly
we'll want here, but I presume you'll be in a good position to judge, Nick,
since Skylab will likely be in the business of generating certs and
provisioning trust stores to apps.

**Comment by markelliot** [comment]
Right, I'd like to be able to specify a directory as a keystore/trustStore type and just read the pem files inside instead of having to actually make jks files. I think it'd be easier for most FDEs to reason about. Not high priority though.

**Comment by ash211** [comment]
I agree with the intuition that it's easier for folks to reason about a directory of PEM files over the java-specific key stores.  A PEM directory format probably can't cover all misc things a java keystore can do though.  Just hitting the majority case (my single cert with private key, plus the list of certs and public/private CAs that I trust) alone would make this valuable.

Puppet has a directory format that's worth referencing:
https://docs.puppetlabs.com/puppet/latest/reference/dirs_ssldir.html

**Comment by markelliot** [comment]
That spec seems fine. Basically, I figured I'd make a note to explore alternatives to JKS, since I think users can have a hard time reasoning about JKS content, and an easier time reasoning about files on disk that they can just cat. We don't have a meaningful need to protect the JKS file with passwords in most setups, and where we do, we can default to using JKS instead of certs on disk.

**Comment by nmiyake** [comment]
Fixed by #92

**Comment by nmiyake** [comment]
@markelliot or @uschi2000 , can you close this issue since it's been resolved?
