### ISSUE TITLE
Retrofit2Client should append slashes if needed to URI's?

### ISSUE THREAD

**Issue by eshlin** [palantir/conjure-java-runtime#237]
Looks like Retrofit2 requires URI's to end in slash (see https://github.com/square/retrofit/issues/1049).

Since the Palantir convention in configuration files has been to avoid ending URI's with a slash, perhaps the Retrofit2Client should do this automatically. Otherwise, users of the library have to manually do so, as is done in Foundry's ServiceFactory class when creating a DataProxy client.

**Comment by uschi2000** [comment]
Can you provide a failing test case, Elin?

**Comment by uschi2000** [comment]
fixed by #238
