### ISSUE TITLE
SerializableErrorErrorDecoder.java fails on exceptions without a single-string constructor

### ISSUE THREAD

**Issue by TheBeruriahIncident** [palantir/conjure-java-runtime#24]
BLUF: Failure to parse error body for any HTTP statuses other than a few of the most common

In https://github.com/palantir/http-remoting/blob/develop/http-clients/src/main/java/com/palantir/remoting/http/errors/SerializableErrorErrorDecoder.java, "exceptionClass.getConstructor(String.class)" requires that the exception has a constructor that takes a single String. This is reasonable for the HTTP statuses that have a a specific exception made for them (e.g. BadRequestException, ForbiddenException), but for all the other statuses, you have to use either a ClientErrorException or ServerErrorException, which do not have single-string constructors.

Hacky workarounds are possible: I wrote code in Contour the catches HTTP-remoting exception and searches the message for the right HTTP status code. :/

**Comment by markelliot** [comment]
Exception generally requires a single-string-argument constructor — is the issue here that sometimes the Exception class isn't known and so the reflective instantiation fails? (or what's a specific and real Exception class that fails this (fine if you want to send me a private pointer to one)?)

**Comment by TheBeruriahIncident** [comment]
The specific classes are ClientErrorException and ServerErrorException. It's not meaningful to instantiate these without a status code, so there's no string-only constructor. You have to use these if there's not a more specific WebApplicationException for your needs. For example, if you want to throw a 501, you have to throw a new ServerErrorException(Status.NOT_IMPLEMENTED).

**Comment by markelliot** [comment]
Can we special case those two exceptions (since we know about them and they're common JAX-RS exceptions, and we can rematerialize them specifically on the client side)?

I suppose we can also check the constructor exists rather than just completely dying, which is bad behavior.

**Comment by TheBeruriahIncident** [comment]
That seems reasonable (perhaps including WebApplicationException, the parent of both, if only for thoroughness on what people might ever use). Perhaps we check if the single-string constructor exists, and if not, we check if the type is instanceof WebApplicationException, then pull out the Status and use the appropriate constructor?

**Comment by markelliot** [comment]
I'd prefer to check the specialized classes first, then fall back to the single string constructor, and failing that, throw a vanilla WebApplicationException if no deserialization is available.

**Comment by TheBeruriahIncident** [comment]
The reason I avoided that order was only so that we could check instanceof WebApplicationException, but I'm fine with checking WebApplication, ClientError, and ServerError separately.

+1 on throwing vanilla on failure

I'm pretty busy for the rest of today, but I can hopefully have a PR up by tomorrow afternoon (if you're fine waiting that long).

**Comment by markelliot** [comment]
thanks, look forward to the PR.

**Comment by j-baker** [comment]
As a pain-point note, JAX-RS exceptions do some classloader magic with a 'RuntimeDelegate' class, the upshot being that we can't currently run tests that throw ClientErrorExceptions from Eclipse.

I think if you don't have a RuntimeDelegateImpl on your classpath (add jersey-common perhaps?) you won't be able to construct them full stop - I remember the api package not being enough.

**Comment by markelliot** [comment]
I think it'd be okay for us to wrap this stuff with some safety around the reflection calls and just defaulting to an Exception in the end if that's what we need to do.
