### ISSUE TITLE
add JsonExceptionMapper implementation to handle UndeclaredThrowableException

### ISSUE THREAD

**Issue by meditativeape** [palantir/conjure-java-runtime#290]
When using Spark SQL to execute SQL queries, we noticed that parse exceptions are not propagated correctly to the client. Their error messages and original stacktraces are lost:
```
{
  "message": "null",
  "exceptionClass": "java.lang.reflect.UndeclaredThrowableException",
  "stacktrace": ...(jersey/jetty only, nothing spark related)
}
```
The root cause is probably an interoperability issue between Java and Scala. Spark SQL's `sql` endpoint could throw `ParseException`, which is a checked exception, but it's not declared in the signature and apparent no one is there to catch it. So it got wrapped in an `UndeclaredThrowableException` and passed to the `JsonExceptionMapper`, which doesn't know how to handle it. The message and stacktrace of the `UndeclaredThrowableException` itself aren't useful; what's interesting is the `undeclaredThrowable` in it, which unfortunately gets dropped.
@pnepywoda for SA

**Comment by schlosna** [comment]
Again it would be good to be able to specify the ObjectMapper or register additional modules so that one could add https://github.com/FasterXML/jackson-module-scala

**Comment by markelliot** [comment]
The issue here doesn't seem related to an object mapper, if the thing serving this exception up wants to register additional exception mappers it certainly can.

**Comment by ash211** [comment]
Are there docs at https://github.com/palantir/http-remoting for how to register additional exception mappers?

**Comment by markelliot** [comment]
https://jersey.java.net/documentation/latest/representations.html#d0e6754

**Comment by pnepywoda** [comment]
Though we have a runtime exception mapper. Could just change that to a
checked one

**Comment by uschi2000** [comment]
Looks like this is now handled correctly by the RuntimeExceptionMapper
