### ISSUE TITLE
use ThreadPoolExecutor instead of homegrown queueing in AsyncSlf4jSpanObserver

### ISSUE THREAD

**Issue by uschi2000** [palantir/conjure-java-runtime#291]

**Comment by uschi2000** [comment]
Watch for this: https://www.bountysource.com/issues/36319922-offer-pool-size-increasing-executorservice-through-executorservicebuilder

**Comment by schlosna** [comment]
Might be worth taking a look at https://github.com/openzipkin/zipkin-reporter-java/blob/master/core/src/main/java/zipkin/reporter/AsyncReporter.java for the memory bounded reporter implementation.

Another option is a `BoundedWorkerPool` backed by a cached thread pool, see https://github.com/palantir/atlasdb/tree/develop/atlasdb-commons/src/main/java/com/palantir/common/concurrent/BlockingWorkerPool.java which would apply back-pressure if desired.

**Comment by iamdanfox** [comment]
Confirming the Asynclf4jSpanObserver now takes an ExecutorService: https://github.com/palantir/tracing-java/blob/aafb8aa3a39f155ce111c9899b6626d871c653d4/tracing/src/main/java/com/palantir/tracing/AsyncSlf4jSpanObserver.java#L184, so this issue has been fixed.
