### ISSUE TITLE
Make FeignJaxRsClientBuilder take an Observable<ClientConfig>

### ISSUE THREAD

**Issue by jared2501** [palantir/conjure-java-runtime#293]
So that the ClientConfig can be live reloaded.

**Comment by uschi2000** [comment]
So you want t to mutate the client? Why is this better than making a new
client when configuration changes?

**Comment by jared2501** [comment]
Yup, will make a new client per config change.

**Comment by jared2501** [comment]
Hey @uschi2000, was thinking about this a bit more after chatting briefly with @bavardage about moving a project to using observables + live config reloading. It's non-trivial to know where to draw the line. For example, I have a `FooResource` that takes:
- a `FooStore`
- an http-remoting `BarService`
- a bunch of immutables config values

I think a nice rule to apply is: push down the observables as far as they go such that only immutable data structures are Observable's. 

For the `FooStore`, I think it would be nice to not take an `Observable<FooStore>` for a couple reasons: 
1. The `InMemoryFooStore` can no longer store its state internally in a hashmap if everytime some property on it changes. 
2. The FooStore implementation is not symetric to the `FooResource` implementation since the `FooResource` take observables and the `FooStore` does not.
3. The `FooResource` implementation becomes fairly verbose and harder to understand with all the `fooStoreObservable.blockingLast()` calls.

For the `BarService`, I could take an `Observable<BarService>`, but since I'm already not taking an `Observable<FooStore>` for the reasons above it would be nice to be able to take a `BarService` for symmetry. I.e. it's unexpected as a reader of some code to see a `FooStore` and an `Observable<BarService>` as fields on the same class.

Thoughts?

**Comment by uschi2000** [comment]
I'm coming around to the idea of making service clients mutable.

**Comment by uschi2000** [comment]
Before adding a dependencies on Observable, we could make the underlying URL list mutable so that the client picks up changing URLs automatically. What type of information needs to be dynamic?

**Comment by jared2501** [comment]
@uschi2000 - I think it would be good to make anything that can be mutable, be mutable. I.e. everything on `ClientConfig`.

Reason being in your witchcraft `RuntimeConfiguration` everything there is expected to be mutable and so if some fields in your http-remoting `ServiceDiscoveryConfiguration` weren't updatable it would be unexpected.

**Comment by jared2501** [comment]
Taking `Supplier<ClientConfig>` could be a nice way to do this?

**Comment by uschi2000** [comment]
It's not a trivial change since the underlying Feign clients are not
mutable. So we'll likely have to introduce another layer of delegation that
always holds an up-to-date instance of the Feign client.

**Comment by markelliot** [comment]
this is resolved now, yeah?

**Comment by bavardage** [comment]
yar
