### ISSUE TITLE
TrustStoreConfiguration is not serializable

### ISSUE THREAD

**Issue by jiahuijiang** [palantir/conjure-java-runtime#30]
Tried to serialize a TrustStoreConfiguration object and got the following exception:

com.fasterxml.jackson.databind.JsonMappingException: Direct self-reference leading to cycle (through reference chain: com.palantir.trust.Json["trustStorePath"]->sun.nio.fs.UnixPath["parent"]->sun.nio.fs.UnixPath["root"])

Is it meant to be like this?

**Comment by markelliot** [comment]
Had assumed this wasn't something that ever needed to be serialized, what's the use-case?

**Comment by jiahuijiang** [comment]
We are trying to pass some information from one process to another spark-submit process using a file. And the trust store configuration is part of it.

**Comment by schlosna** [comment]
It's failing on the path to the trust store on disk, which likely isn't even a valid path on the workers.
What is being serialized that is referencing the trust store config? Do you actually want to serialize the trust store config in that case?

**Comment by schlosna** [comment]
If you do actually want this, you could use https://github.com/FasterXML/jackson-datatype-jdk7 (specifically see https://github.com/FasterXML/jackson-datatype-jdk7/issues/1 )

**Comment by jiahuijiang** [comment]
The driver will be the only one that's using the trust store. And it will be on the same box as the process that forked this spark-submit process.
Thanks for the link!

**Comment by markelliot** [comment]
Pretty simple to fix this. Will adjust in a bit.

**Comment by markelliot** [comment]
hm, actually, I'd expect this to work, will need to do some testing

**Comment by jiahuijiang** [comment]
@markelliot I followed the link @schlosna sent and registered the jdk7 module to the ObjectMapper and it's working now :) Thanks for taking a look at the problem!

**Comment by tpetracca** [comment]
FYI the change made in #52 doesn't address the issue here (although adding the jdk7module does so I'm just going to do that), because SslConfiguration still uses java.nio.file.Path.

Edit: I now realize this specific issue was TrustStoreConfiguration, which no longer exists.  I think this issue may have regressed when we (what I assume was a refactor) removed TrustStoreConfiguration and KeyStoreConfiguration in favor of SslConfiguration.
