### ISSUE TITLE
slf4j LinkageError when using http-remoting inside an application with multiple classloaders.

### ISSUE THREAD

**Issue by mwakerman** [palantir/conjure-java-runtime#308]
dep:version: `jaxrs-clients:1.0.3`

We use `http-remoting` inside a plugin that has a separate classloader to the parent application. When attempting to initialise this plugin, we get a `LinkageError` when the classloader attempts to load the `org.slf4j.ILoggerFactory`class (stacktrace below). The application classloader brings in the `slf4j` API and implementation libraries (`slf4j-api` and `slf4j-log4j12`). And it appears that `jaxrs-clients` brings in the slf4j API classes directly (and UN-shaded). Is this an intentional and/or can the slf4j classes be moved to the shaded package?

(minor cosmetic changes made to stacktrace below)
```ERROR [NotAwt created from {AWT-EventQueue-2}] com.company.platform.Registry - Could not instantiate custom helper due to exception thrown during initialization.
java.lang.LinkageError: loader constraint violation: when resolving method "org.slf4j.impl.StaticLoggerBinder.getLoggerFactory()Lorg/slf4j/ILoggerFactory;" the class loader (instance of com/company/plugin/impl/PluginClassLoader) of the current class, org/slf4j/LoggerFactory, and the class loader (instance of java/net/URLClassLoader) for resolved class, org/slf4j/impl/StaticLoggerBinder, have different Class objects for the type org/slf4j/ILoggerFactory used in the signature
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:335)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:283)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:304)
	...```

**Comment by uschi2000** [comment]
Slf4j is intentionally non-shaded

**Comment by j-esse** [comment]
Can we just not bundle slf4j?   I guess you really don't want http-remoting to have any dependencies?

**Comment by uschi2000** [comment]
I believe we have to bundle the API at least. Don't have a laptop, so
cannot check right now. Generally always happy to remove dependencies if
possible.

**Comment by j-esse** [comment]
I'd strongly push for not bundling any non-shaded classes (i.e. slf4j and javax-annotations in this case), I've seen heaps of issues with this kind of thing in the past.  Could we publish two version of http-remoting, one with the dependencies bundled, and one without (and gradle will pull the deps in)?

**Comment by uschi2000** [comment]
Jesse, I agree with your sentiment. Bundling non-shaded classes is a bug in the jaxrs-clients build script. I won't have time to tackle this until end of next week or so, but would appreciate a contribution.

**Comment by j-esse** [comment]
Ah cool, we'll take a look at fixing the build script then. Thanks!

**Comment by mwakerman** [comment]
I've got a fix for this on a fork, just testing it out and then will submit a PR.

**Comment by markelliot** [comment]
happy to see a PR for this, any updates?

**Comment by mwakerman** [comment]
@markelliot - apologies for the delay, ended up being a simple fix but we needed Java 6 compatibility.
