### ISSUE TITLE
Kebab-case ServiceDiscoveryConfiguration

### ISSUE THREAD

**Issue by jared2501** [palantir/conjure-java-runtime#315]
So that we can used `ServiceDiscoveryConfiguration` with jackson 2.7- (since spark requires jackons 2.6.5).

**Comment by jared2501** [comment]
@uschi2000 @markelliot - would you guys be OK if I submitted this as a new class called `KebabCasedServiceDiscoveryConfiguration` (or something similar) to `service-config`?

**Comment by uschi2000** [comment]
don't quite follow what exactly you're proposing? can you elaborate?

**Comment by jared2501** [comment]
proposing that I copy + paste the current ServiceDiscoveryConfiguration and JsonProperty annotate it so that it deserializes from a kebab-cased version

**Comment by uschi2000** [comment]
I see. Can we instead make the existing class more lenient?

**Comment by jared2501** [comment]
How do you propose we do this?

**Comment by uschi2000** [comment]
I don't know; maybe there is a way in Jackson?

**Comment by jared2501** [comment]
@markelliot found a way, but it requires jackson 2.7. We can't go to 2.7 in projects that require spark ;(

**Comment by markelliot** [comment]
Jackson 2.7+ supports, but we're stuck on 2.6.5 for Spark, generally. We could shade Jackson to do config parsing, or choose something other than Jackson for config parsing (maybe not the worst idea).

**Comment by jared2501** [comment]
Alternatively I could also write a custom Jackson deserialiser?

**Comment by jared2501** [comment]
The custom jackson deserializer could be just for the `ServiceDiscoveryConfiguration` class

**Comment by markelliot** [comment]
Custom deserializer would be most general way to do it, and can be wired in using Jackson 2.6.5. Perhaps best possible variant: build a custom deserializer generator as part of immutables?

**Comment by jared2501** [comment]
You mean propose a change to Immutables that does that?

**Comment by jared2501** [comment]
For now, I might hand write one since we require this this week, but am open to contributing it back to immutables

**Comment by markelliot** [comment]
There's a plugin infra for immutables now. Shrug, handwriting one here is probably fine.

**Comment by uschi2000** [comment]
If this is all too complicated then we can also make the simpler change here. (Although I'd prefer the more sustainable change)

**Comment by markelliot** [comment]
Best option is likely the custom deserializer – we'd ideally support either camel case or kebab case and simply move to preferring kebab case.

**Comment by jared2501** [comment]
sweet! one custom deserializer coming right up
