### ISSUE TITLE
Remove kebab-case builder methods when jackson 2.7 is picked up

### ISSUE THREAD

**Issue by jared2501** [palantir/conjure-java-runtime#317]
Currently, config classes have builder methods that support kebab-case properties. This is required if the kebab-case config format of the config classes is to be supported. When jackson 2.7 is picked up, these builder overrides can be removed since the ObjectMapper can be configured to allow kebab-case properties to be deserialized.

**Comment by uschi2000** [comment]
Cannot move to 2.7 yet :(

**Comment by jared2501** [comment]
@markelliot showed me

https://github.com/FasterXML/jackson-annotations/blob/master/src/main/java/com/fasterxml/jackson/annotation/JsonAlias.java

**Comment by SerialVelocity** [comment]
@uschi2000 Why can't we move to 2.7 yet?

**Comment by uschi2000** [comment]
Spark!

**Comment by ash211** [comment]
https://github.com/apache/spark/blob/master/pom.xml#L164
