### ISSUE TITLE
Enable Jackson Afterburner module

### ISSUE THREAD

**Issue by schlosna** [palantir/conjure-java-runtime#324]
When we bump to Jackson 2.6+ (#323), might want to [enable the Jackson afterburner module](https://github.com/FasterXML/jackson-module-afterburner). Note that we will need to test with both Jackson 2.6.x & 2.7.x+ as Afterburner is included in [jackson-modules-base](https://github.com/FasterXML/jackson-modules-base) as of Jackson 2.7.1.

**Comment by markelliot** [comment]
We've been applying afterburner/have been on 2.6 for a while now. It's only selectively disabled for 2.4 codepaths (but that was just removed).

**Comment by uschi2000** [comment]
https://github.com/palantir/http-remoting/blob/develop/extras/jackson-support/src/main/java/com/palantir/remoting1/ext/jackson/ObjectMappers.java#L40
