### ISSUE TITLE
Consider retrying DNS resolution

### ISSUE THREAD

**Issue by uschi2000** [palantir/conjure-java-runtime#346]

**Comment by pnepywoda** [comment]
Can we get a little more context? :)

**Comment by uschi2000** [comment]
Current behavior: when DNS resolution fails for a service, it'll try the next host, but it won't retry the DNS resolution for the present one.
Proposed behavior (maybe, I'm not convinced this is the right thing to do yet): retry DNS resolution for the present URL.

**Comment by uschi2000** [comment]
Unclear we need to do this, closing for now.
