### ISSUE TITLE
Dynamically building URI strings from Dropwizard App Rules

### ISSUE THREAD

**Issue by dotCipher** [palantir/conjure-java-runtime#348]
I am not sure if this is something that fits in the scope of this library but one could leverage some of the exposed API from the [`DropwizardAppRule`](https://github.com/dropwizard/dropwizard/blob/master/dropwizard-testing/src/main/java/io/dropwizard/testing/junit/DropwizardAppRule.java) to build URIs for http-remoting clients within tests dynamically.

I end up using http-remoting heavily in tests for Dropwizard stacks, and this would make things even easier.

Thoughts?

**Comment by uschi2000** [comment]
Can you give an example?

**Comment by dotCipher** [comment]
I do something like this in my tests:

```
DropwizardUri.Builder builder = DropwizardUri.builder().admin(admin);
        AbstractServerFactory serverFactory = (AbstractServerFactory) appRule.getConfiguration().getServerFactory();
        builder.rootJerseyPath(parseJerseyRootPath(serverFactory.getJerseyRootPath()));
        if (serverFactory instanceof SimpleServerFactory) {
            builder.connectorFactory(((SimpleServerFactory) serverFactory).getConnector());
        } else {
            DefaultServerFactory defaultServerFactory = ((DefaultServerFactory) serverFactory);
            if (admin) {
                builder.connectorFactory(CONNECTOR_FACTORY_REDUCTION_FUNCTION.apply(
                        defaultServerFactory.getAdminConnectors()));
            } else {
                builder.connectorFactory(CONNECTOR_FACTORY_REDUCTION_FUNCTION.apply(
                        defaultServerFactory.getApplicationConnectors()));
            }
        }
        builder.port(admin ? appRule.getAdminPort() : appRule.getLocalPort());
        return builder.build();
```

Then calling `toString`:
```
public String toString() {
        return String.format("%s://%s:%d%s", protocol(), hostname(), port(), rootJerseyPath());
    }
```

**Comment by uschi2000** [comment]
Why not do something like this?

    @ClassRule
    public static final DropwizardAppRule<Configuration> server =
            new DropwizardAppRule<>(TestEchoServer.class,
"src/test/resources/test-server-ssl.yml");

    @Test
    public void test() throws Exception {
        String endpointUri = "https://localhost:" + server.getLocalPort();
    }

**Comment by uschi2000** [comment]
I don't think we're going to add Dropwizard-related stuff here.

**Comment by dotCipher** [comment]
Makes sense, thanks!
