### ISSUE TITLE
Support for JSR310 type deserialization

### ISSUE THREAD

**Issue by dotCipher** [palantir/conjure-java-runtime#352]
Similar to #241 but would it be possible to surface a way to generate a client that allows for JSR310 deserialization?  I have an API that uses `ZonedDateTime` types and would like to be able to use `http-remoting` for both testing and automation.

**Comment by markelliot** [comment]
This is already merged into the 2.0.0 branch. Rob, do you have a sense of when we'll release 2.0.0?

**Comment by uschi2000** [comment]
We have F1.0 working with the 2.0.0-alpha, so from my perspective it's ready to go

**Comment by henryptung** [comment]
One flag here: For services that had types previously serializing Joda dates as timestamps, this doesn't provide a migration path. AFAIK, you can use `@JsonFormat(with/without = ...)` to configure the property to serialize to string, to millis, or to `seconds.nanos`, but you cannot configure deserialization there (in particular, epoch-millis values from older versions of the service will be misinterpreted, and without a way to configure the ObjectMapper, I'm not aware of a way around.

I'm not sure how many folks have `seconds.nanos` values in their API, but for safety, wouldn't disabling `DeserializationFeature.READ_DATE_TIMESTAMPS_AS_NANOSECONDS` be a saner default, to preserve wire-format backwards-compatibility with Joda serialization?

**Comment by markelliot** [comment]
The changes made here didn't touch Joda, but instead focused on the Java 8 native time types defined in JSR310. If you previously used annotations on your classes to customize behavior of things like Java 8's ZonedDateTime or Duration, then I think those will take precedence, but feel free to submit a failing test case if you have one (please submit to a new issue, it's distinct from applying the JavaTime module).

In the meantime, this is resolved.
