### ISSUE TITLE
If not propagating stacktrace, actually log

### ISSUE THREAD

**Issue by henryptung** [palantir/conjure-java-runtime#357]
https://github.com/palantir/http-remoting/blob/develop/jersey-servers/src/main/java/com/palantir/remoting2/servers/jersey/JsonExceptionMapper.java#L65

This seems to log only the exception message, not the full exception, which means the stacktrace is permanently lost after this point.

**Comment by uschi2000** [comment]
Typically, the server (e.g., jersey) would log the exception that gets into this mapper. Is that not the case?

**Comment by henryptung** [comment]
@uschi2000 I think that's the `ExceptionMapper`'s job. See `LoggingExceptionMapper` in Dropwizard.

**Comment by uschi2000** [comment]
You're right, thanks. https://github.com/palantir/http-remoting/pull/358

**Comment by jared2501** [comment]
Hey @markelliot @uschi2000 - can we get a release with this in it?

**Comment by uschi2000** [comment]
This should be on 2.0.0, no?
