### ISSUE TITLE
possible to say which server caused RemoteException?

### ISSUE THREAD

**Issue by sjrand** [palantir/conjure-java-runtime#362]
Lately I've observed various error messages which tell me to consult the logs for "the server" (https://github.com/palantir/http-remoting/blob/42868e6b7dbcb0b16dc3840ceab0a838661ce963/jersey-servers/src/main/java/com/palantir/remoting2/servers/jersey/JsonExceptionMapper.java#L66).

However, it is often unclear to me which server is the culprit, and I go digging through multiple log files before finding the right one. Is there any way to provide more information about which server to check for errors?

**Comment by markelliot** [comment]
anticipated workflow here would be going to the central log viewer we run and searching for the traceId, which would let you see everything associated with this error not just the origin server.
