### ISSUE TITLE
GuavaOptionalAwareContract turns all absent header params into {header name}

### ISSUE THREAD

**Issue by j-baker** [palantir/conjure-java-runtime#37]
See https://github.com/palantir/http-remoting/blob/develop/http-clients/src/test/java/com/palantir/remoting/http/GuavaOptionalAwareContractTest.java#L117

This is never the behaviour you want. Imagine someone not providing an optional `Accept` header and actually ending up requiring something of type `{Accept}`.

Alternatively, imagine someone making a request without an `If-Match` header, and actually demanding an `If-Match` header of `{If-Match}`.

**Comment by j-baker** [comment]
The fix is probably to more deeply integrate this with the JAXRS contract.

**Comment by markelliot** [comment]
proposed a fix in #38, nothing JAX-RS specific.

**Comment by markelliot** [comment]
fixed in #38
