### ISSUE TITLE
Does http-remoting automatically lower case uris?

### ISSUE THREAD

**Issue by rahij** [palantir/conjure-java-runtime#377]
I'm generating a Retrofit2Client with a URI whose FQDN has upper case letters. When I actually make a request with that client, I hit this error: https://github.com/palantir/http-remoting/blob/ae3be5349b1634183798ff52cc5df40925af7840/retrofit2-clients/src/main/java/com/palantir/remoting2/retrofit2/MultiServerRetryInterceptor.java#L101

"Unrecognized server URI in the request `lower case fqdn`. Supported servers are `original upper case fqdn`". 

Should we be doing case insensitive comparisons instead?

cc @uschi2000

**Comment by uschi2000** [comment]
likely would have to compare the host portion case-insensitively and the path portion case-sensitively, right?

**Comment by rahij** [comment]
Yep you're right. Happy to send a PR your way if this indeed is expected http-remoting behavior currently.

**Comment by ash211** [comment]
DNS names should be case-insensitive -- https://tools.ietf.org/html/rfc4343
