### ISSUE TITLE
Adding metadata to traces

### ISSUE THREAD

**Issue by jkozlowski** [palantir/conjure-java-runtime#383]
#In an internal product we are currently heavily instrumenting various codepaths and we would like to be able to add additional metadata to traces, e.g. sizes of responses, various queries etc. The core zipkin spec allows for that, how do we go about exposing that in this library?

As a sidenote, brave 4.0 was released in January and has fixed a lot of the gripes we had with the library and seems to have added better support for async apps.

**Comment by markelliot** [comment]
Presently it's only possible to change the string operation name. As an alternative, you could cooperatively log (and logs will automatically be labeled with traceId) associated information rather than emit it as part of the same event.

Both Rob and I are subscribed to the "internal traces" issue on Brave's repo, and it's still not resolved.

**Comment by jkozlowski** [comment]
I think I should've looked at the code first then... Logging associated information is not ideal, because it will get associated with the server span id, not a local trace, I think, but I suppose it's a start.

**Comment by markelliot** [comment]
The current spanId is available to you, if you want to include it in your log:

    Optional<String> spanId = Trace.top().map(OpenSpan::getSpanId);

**Comment by markelliot** [comment]
Ah sorry, that's bogus advice, you'd have to open a span explicitly:

    try {
        OpenSpan newSpan = Tracer.startSpan("operation");
        // now can access: newSpan.getSpanId();
    } finally {
        Tracer.completeSpan();
    }

**Comment by markelliot** [comment]
...but would be open to adding one of these to Tracer:

 * `Optional<OpenSpan> getCurrentSpan()`
 * `Optional<String> getSpanId()`

**Comment by jkozlowski** [comment]
Cool, I can figure out a workaround. Question is, whether we are open to adding something more systematic that will allow me to attach those through the API, not by logging my own messages and how would we go about that.

**Comment by jkozlowski** [comment]
https://github.com/openzipkin/brave/issues/166 just merged

**Comment by jkozlowski** [comment]
Fixed in #429
