### ISSUE TITLE
Implement a Java8OptionalMessageBodyReader

### ISSUE THREAD

**Issue by cihati** [palantir/conjure-java-runtime#389]
Dropwizard/Jersey does not handle Optional<T> in a request body (i.e. a `null` is passed, rather than `Optional.empty()` )

DW has some logic for Optionals ( https://github.com/dropwizard/dropwizard/tree/master/dropwizard-jersey/src/main/java/io/dropwizard/jersey/optional ), but not for POST body handling.

cc @markelliot

**Comment by tpetracca** [comment]
@palantir/infrastructure is it safe to assume that the move to conjure + our default objectmappers fixed this?
