### ISSUE TITLE
Blacklisted cipher suites in remoting for http2

### ISSUE THREAD

**Issue by justinuang** [palantir/conjure-java-runtime#394]
The following is thrown by the asset-server when contacted by a Feign client created with remoting

    server rejecting conn: INADEQUATE_SECURITY, Prohibited TLS 1.2 Cipher Suite: c014

which it is allowed to do for http2 (https://http2.github.io/http2-spec/#BadCipherSuites)

    An HTTP/2 implementation MAY treat the negotiation of any of the following cipher suites with TLS 1.2 as a connection error (Section 5.4.1) of type INADEQUATE_SECURITY:

The client in remoting uses TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA: https://github.com/palantir/http-remoting/blob/develop/http-clients-api/src/main/java/com/palantir/remoting2/clients/CipherSuites.java

**Comment by justinuang** [comment]
@markelliot so it sounds like we need to lists of cipher suites? Could we loop in infosec on exactly what list to use?

**Comment by justinuang** [comment]
@robert3005 and I were discussing and we were thinking if we could just take the http1 list, remove the blacklisted one, and just use that for both http1 and 2. That way, we don't have to detect whether the agent was applied, and the restrictions might not be too bad. Thoughts?

**Comment by markelliot** [comment]
Sure, that's probably fine. There's more than one entry in this list on the TLS1.2 blacklist.

**Comment by nziebart** [comment]
actually all of the entries in the "fast" cipher suites are blacklisted

**Comment by uschi2000** [comment]
this has been idle for a while, closing
