### ISSUE TITLE
client objectmapper javadoc inconsistent with impl

### ISSUE THREAD

**Issue by bavardage** [palantir/conjure-java-runtime#397]
https://github.com/palantir/http-remoting/blob/develop/extras/jackson-support/src/main/java/com/palantir/remoting2/ext/jackson/ObjectMappers.java#L52

the doc says it ignores unknown properties

which is the desired behaviour? (I can throw up a PR)

**Comment by markelliot** [comment]
This is correct/consistent already; the Jackson settings are a bit annoying to read, but we're disabling the fail-on-unknown error, which means it accepts unknown properties.

**Comment by bavardage** [comment]
eep sorry, misread.
