### ISSUE TITLE
Jackson ObjectMapper config changes

### ISSUE THREAD

**Issue by markelliot** [palantir/conjure-java-runtime#398]
I propose we:
 - if a field is Optional.absent/Optional.empty we omit the field vs. explicit null
 - if a field is an empty map, set or list we omit the field vs. explicit empty

**Comment by uschi2000** [comment]
Assume this related to both body objects query parameters?

**Comment by markelliot** [comment]
yep

**Comment by iamdanfox** [comment]
I'd still like this change to happen - http-remoting currently sends JSON like the following, which doesn't match the conjure wire format recommendations:

```yml
{
  "foo": null
  "bar": null
}
```
