### ISSUE TITLE
Is @Context supported for JaxRsClientBuilder?

### ISSUE THREAD

**Issue by dev-kpyc** [palantir/conjure-java-runtime#406]
I am trying to create a JaxRsClient for an api I'm working with. The api has a method which has a body param and an httpServletRequest annotated with @Context as shown below:

```

@POST
FooResponse Foo(FooRequest request, @Context HttpServletRequest request)
```

When I try to construct the client using JaxRsClient.builder, I get 
"java.lang.IllegalStateException: Method has too many Body parameters" pertaining to this method. The issue is that the @Context annotation is not causing this parameter to be recognized as not a body parameter.

Is this an issue with how the JaxRsClient is being configured? Or is this simply not supported at some level?

**Comment by dev-kpyc** [comment]
@markelliot @uschi2000

**Comment by markelliot** [comment]
Yeah, not supported. What would a client put in that method argument?

**Comment by dev-kpyc** [comment]
The simple thing would be that the argument is ignored. You would need to be okay with the server receiving the request with whatever context is already there

**Comment by markelliot** [comment]
Yeah, underneath the covers this thing delegates to other impls, those don't support the functionality and I don't think we're going to add support for it.

**Comment by dev-kpyc** [comment]
Ok thanks, I'll look for another solution to test this api
