### ISSUE TITLE
Bump major version to reflect backcompat break?

### ISSUE THREAD

**Issue by derenrich** [palantir/conjure-java-runtime#409]
Does this repo follow semantic versioning? 

If so shouldn't we be on 3.0.0 now given remoting took a backcompat-break for version 2.3.0? 

I just got bit by that backcompat break.

**Comment by markelliot** [comment]
What break?

On Apr 19, 2017, at 10:24 PM, Daniel Erenrich <notifications@github.com<mailto:notifications@github.com>> wrote:


Does this repo follow semantic versioning?

If so shouldn't we be on 3.0.0 now given remoting took a backcompat-break for version 2.3.0?

I just got bit by that backcompat break.

**Comment by derenrich** [comment]
See the release notes for the last release

**Comment by markelliot** [comment]
It might be better called a "change" or an "alert", there was no semver break here.  In particular, no code will stop working, compiling, or running/things are still semantically, source and binary compatible.

On Apr 20, 2017, at 12:20 AM, Daniel Erenrich <notifications@github.com<mailto:notifications@github.com>> wrote:

See the release notes for the last release

**Comment by derenrich** [comment]
My code broke? And then worked when I downgraded? I mean I guess that's not
*proof* per se. But ok.

**Comment by markelliot** [comment]
What broke?

On Apr 20, 2017, at 12:36 AM, Daniel Erenrich <notifications@github.com<mailto:notifications@github.com>> wrote:

My code broke? And then worked when I downgraded? I mean I guess that's not
*proof* per se. But ok.

**Comment by derenrich** [comment]
I mean the change requires that user's of the library to install the Http2Agent whereas before it was installed for you. 
 
>- The framework using remoting should be responsible for installing the
>  Http2Agent (for example witchcraft or spark-module-lib), as to ensure
>  that it is done early enough.

I hit this issue when upgrading from an older version of witchcraft. While I still think this should be bumped in retrospect at this point bumping it won't solve any problems so I'm closing this.

**Comment by ash211** [comment]
I had to make two changes to accommodate this:

- add dependency on `compile 'com.palantir.remoting2:http2-agent'`
- put this as a static block on the class with my main method:

```
static {
    Http2Agent.install();
}
```

**Comment by markelliot** [comment]
Neither change was required, though, http 1.1 support would've continued to give you full functionality.

On Apr 20, 2017, at 9:56 AM, Andrew Ash <notifications@github.com<mailto:notifications@github.com>> wrote:


I had to make two changes to accommodate this:

  *   add dependency on compile 'com.palantir.remoting2:http2-agent'
  *   put this as a static block on the class with my main method:

static {
    Http2Agent.install();
}
