### ISSUE TITLE
Connect zipkin traces across Spark jobs

### ISSUE THREAD

**Issue by ash211** [palantir/conjure-java-runtime#420]
I'd like to be able to tie a zipkin trace from my service out to the Spark job it launches and through to the API calls that the Spark executors are making on to other services.  I don't have full control over the calls from Spark driver to the executors though, as that cluster activity is managed by Spark and I believe is not zipkin aware.

However Spark does support setting local `String` properties on a Spark job which are accessible on the executors.  So I could possibly plumb a trace to the executors by serializing it as a String through a Spark local property and deserializing on the other side in each Spark task, re-initing the trace.

This would need a similar ser/de pair as `OkhttpTraceInterceptor` / `TraceEnrichingFilter` which serialize an active trace across an HTTP call.

A potential downside here could be that the same trace is re-initialized identically many times across the Spark executors, potentially confusing any subsequent analysis mechanisms.

Does this approach make sense?  I'm currently unsure what the deserialization mechanism in Spark would be for setting up the traces for arbitrary jobs (unless we could hook this into our common library that Spark jobs run through).

cc @robert3005 @schlosna

**Comment by schlosna** [comment]
Will have to look into this, should be feasible if we can propagate trace ID and parent ID from driver to executors.

**Comment by ash211** [comment]
When we eventually get to this, going to do it in a generic way that's not http-remoting specific: https://issues.apache.org/jira/browse/SPARK-21962

**Comment by markelliot** [comment]
Nothing about our distributed tracing is http-remoting specific. We use the standard Zipkin specs and cross-service comms between our Java and Go programs work just fine.
