### ISSUE TITLE
Non-deterministic OptionalMessageBodyWriter selection - Dropwizard 1.0, 1.1 

### ISSUE THREAD

**Issue by felixdesouza** [palantir/conjure-java-runtime#427]
Prior to Dropwizard 1.x, to be able to write out `Optional`'s you had to make use of the `Java8Bundle` (this added an `OptionalMessageBodyWriter`) since Dropwizard supported Java 7 and hence could not pick up Java 8 Optionals.

As 1.x got released and became Java 8 only, the bundle was deprecated and its behaviour inlined (mostly in `DropwizardResourceConfig`). The downside to this is that the `OptionalMessageBodyWriter` selection by the Jersey runtime is non-deterministic if you have more than one i.e. remoting2 and its 204 scheme vs Dropwizard's `OptoionalMessageBodyWriter`.

This is only *potentially* remedied with a kick of the server (it can always be stuck on. There are 2 options I think:
* Register the `OptionalMessageBodyWriter` with a priority (this will work with 1.0 and 1.1):
```java
context.register(Java8OptionalMessageBodyWriter.class, 1);
```
* Or somehow provide an `ExceptionMapper` for the `EmptyOptionalException` that gets thrown in DW 1.1's `OptionalMessageBodyWriter`. Upshot is that the mapper can define the behaviour we want in remoting2 and we no longer have to register the `Java8OptionalMessageBodyWriter`. Downside is that a dropwizard dependency will be added on this library (unless it's a separate project akin to `jersey-servers`), and also it only supports DW 1.1. Dropwizard 1.0.x cannot work this way without the priority hack. They introduced it in 1.1 dropwizard/dropwizard#1784 due to dropwizard/dropwizard#1727 and @qinfchen.

This came about because we had upgraded to DW ~~1.0~~ 1.1 and I was trying to show that the Java 8 bundle was no longer necessary, but our tests were failing because of 404s instead of 204s.

Thoughts? I'm biased towards the latter option, and making a hard requirement on DW 1.1, which should be fine, as there shouldn't be any breaks that I'm aware of.

NB: Both of these can be done by the consumer, so even if none of the options above make it through, perhaps some sort of signalling?

**Comment by uschi2000** [comment]
@nziebart what did you end up doing here?

**Comment by qinfchen** [comment]
@felixdesouza, can you do something like [this](http://www.dropwizard.io/1.1.0/docs/manual/core.html#overriding-default-exception-mappers)?

**Comment by nziebart** [comment]
We registered an exception mapper for `EmptyOptionalException` (the recommended approach by Dropwizard), although we ended up not going with DW1 and instead switched to the internal product.

The gist was adding this line in the `run` method:
```
environment.jersey().register(new EmptyOptionalTo204ExceptionMapper());
```

**Comment by felixdesouza** [comment]
I suppose I hadn't written what I ended up doing. I did the second option (or exactly the thing you sent @qinfchen) as it was most straightforward/seemed the most elegant. I was merely raising the issue to see what library support could come with remoting.

**Comment by uschi2000** [comment]
This seems stale or no longer needed? Closing for now.

**Comment by fushar** [comment]
Hey guys, I have just spent several hours trying to figure out why my personal project with DW 1.1 returns inconsistent HTTP status for empty optional, before recalling that we're still having this open issue.

This issue effectively makes this library doesn't work out of the box with DW 1.1, which is unpleasant, especially with the fact that `Optional<>` as return type in API endpoints is common.

I ended up registering the correct exception mapper `EmptyOptionalException` as what the others have already done, but this is something that should be called out in the readme. Better yet, we should fix this for DW 1.1, potentially by making a hard dependency to it as @felixdesouza explained above.

I am more than happy to submit a PR for mentioning the "workaround" in the readme, at least for the time being, if you guys don't mind? Thoughts?

**Comment by uschi2000** [comment]
Sure, happy to add this to the readme. Even better, want to make a PR to get remoting to be DW 1.x compatible?

**Comment by fushar** [comment]
Hmm, how about making a separate `dropwizard1-servers` library, which depends on `jersey-servers` and additionally has `HttpRemotingDropwizard1Feature` which registers all features of `HttpRemotingJerseyFeature` plus the correct mapper for empty `Optional`?

This way 0.x/non-DW users can still depend on `jersey-servers`.

**Comment by uschi2000** [comment]
yes, that works.

**Comment by fushar** [comment]
I've played around a bit with the implementation, but right now I'm stuck in making the test works. I'm using `dropwizard-testing` version 1.1.x, but it depends on Jackson and Guava versions that are higher than our `versions.props`, causing various issues at runtime.

Any idea on how to "fix" this? I'm not super familiar but can `testCompile` dep versions be different than the `compile` ones? Or is this even a good idea at all?

**Comment by uschi2000** [comment]
we generally generally bump jackson before remoting 4.0.0 (at the earliest). if you bump jackson for tests only (yes, this is possible in gradle), then you likely run into issues with some jars not being available in that version? not sure how to reconcile this.
