### ISSUE TITLE
Upgrade OkHttp to 3.7

### ISSUE THREAD

**Issue by jamesthomp** [palantir/conjure-java-runtime#431]
OkHttp fixed the SSL negotiation in IBM Java in 3.7 https://github.com/square/okhttp/issues/3173
Once upgraded, remove the workaround: https://github.com/palantir/http-remoting/pull/430

**Comment by schlosna** [comment]
Worth noting that [okhttp 3.8.0](https://github.com/square/okhttp/blob/master/CHANGELOG.md) is out now as well as [okio 1.13.0](https://github.com/square/okio/blob/master/CHANGELOG.md)

**Comment by jamesthomp** [comment]
fixed by #433
