### ISSUE TITLE
JaxRsClient should allow more config

### ISSUE THREAD

**Issue by carrino** [palantir/conjure-java-runtime#437]
The main thing missing in JaxRsClient is the ability to pass an ObjectMapper.

Another useful method would be to create a javax.ws.rs.client.Client or javax.ws.rs.client.WebTarget based on a ServiceConfiguration.  This would be a good generic work around for cases that don't fit into the proxy like javax.ws.rs.core.StreamingOutput or mappers that aren't in the default set. Then the ssl, timeout, proxy and api token params could be set up correctly for http calls even if we can't use the proxy

**Comment by uschi2000** [comment]
Hej John,
At this point, we are thinking of http-remoting as opinionated RPC library
rather than a generic http library. To this end, it's important for the
wire format to be stable and thus the object mapper is the same for all
services.
  R.

**Comment by carrino** [comment]
I think it reduces a lot of the usefulness of the service-config if you can't construct endpoints for all services.  I think a ClientBuilder that has the ssl context and proxy and api token set up will make service-config stronger and not take anything away from the jaxrs proxy.

**Comment by uschi2000** [comment]
Sure, that we can do.

**Comment by carrino** [comment]
something like this: https://github.com/palantir/http-remoting/pull/450

**Comment by carrino** [comment]
I was really hoping this would make it into remoting3.  I've had to use our backup Feign Proxy with no support for failover or any of the other stuff just because I needed something in the object mapper.

**Comment by carrino** [comment]
also I think just because an api has uploads or something else, doesn't mean it shouldn't be configured in the same way using the same service config block in "that one internal service that does discovery and produces blocks"

**Comment by uschi2000** [comment]
Can you check out the OkHttpClients class on develop and see if that works for you?

Sent from Email+ secured by MobileIron

-------- Original Message --------
