### ISSUE TITLE
Use a global okhttp client

### ISSUE THREAD

**Issue by uschi2000** [palantir/conjure-java-runtime#445]
Should this be injected or a static instance?

**Comment by markelliot** [comment]
Likely a static instance. (That’s what OkHttp docs recommend.)

**Comment by uschi2000** [comment]
Using a single instance is probably not necessary (since different proxies likely talk to different hosts and thus need different connections, i.e., you don't get much pooling/sharing benefit) and hard to implement because different proxies may be configured with different SSL and timeout etc settings.
