### ISSUE TITLE
User Agent Requirements

### ISSUE THREAD

**Issue by mnazbro** [palantir/conjure-java-runtime#449]
There are user agent naming requirements which are caught at remote call time rather than at user agent creation time. Using `UserAgents.fromClass`, you can construct a user agent that doesn't match the regex here: https://github.com/palantir/http-remoting/blob/develop/retrofit2-clients/src/main/java/com/palantir/remoting2/retrofit2/UserAgentInterceptor.java#L30

**Comment by uschi2000** [comment]
yep, fair. want to make a PR?

**Comment by uschi2000** [comment]
no longer relevant, I believe
