### ISSUE TITLE
Change TraceEnrichingFilter to Include traceId on the initial request 

### ISSUE THREAD

**Issue by k-simons** [palantir/conjure-java-runtime#467]
- Per discussions with @gracew, right now what can happen on a simple request is:
- a web client makes a request to a backend service without a X-B3-TraceId header -> in the backend service, TraceEnrichingFilter generates a TraceId but does not add it to the request -> request completes -> request is logged without a X-B3-TraceId header
- We would like to change TraceEnrichingFilter in this example so the backend service also has the traceId generated
- Therefore, when searching on traceId, you will also get the originating service

**Comment by uschi2000** [comment]
What do you mean by "add it to the request"? Today, we do this:
```
        MDC.put(MDC_KEY, Tracer.getTraceId());

        // Give asynchronous downstream handlers access to the trace id
        requestContext.setProperty("com.palantir.remoting2.traceId", Tracer.getTraceId());
```

**Comment by k-simons** [comment]
Root cause of this was unrelated to the TraceEnrichingFilter
