### ISSUE TITLE
Is it reasonable to register OptionalAsNoContentMessageBodyWriter at the same time as all the ExceptionMappers?

### ISSUE THREAD

**Issue by TheBeruriahIncident** [palantir/conjure-java-runtime#47]
Right now, it appears that client apps ought to be calling `ExceptionMappers.visitExceptionMappers`, followed by registering `OptionalAsNoContentMessageBodyWriter` separately, making it easy to forget. Is it reasonable to include `OptionalAsNoContentMessageBodyWriter` in the registering visitor? (this probably needs a rename of `ExceptionMappers`)

**Comment by markelliot** [comment]
we've changed registration to use a Jersey feature, which makes this all sane.
