### ISSUE TITLE
User Agent uses non-standard format

### ISSUE THREAD

**Issue by bmoylan** [palantir/conjure-java-runtime#470]
http-remoting currently creates user-agent strings of the format `<product-name> (<product-version>)`, while the majority of the internet uses `<product-name>/<product-version>`.

Reference:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent
https://en.wikipedia.org/wiki/User_agent

Is there any reason for the nonstandard behavior?

**Comment by markelliot** [comment]
It's not a formal spec so we picked something readable. We should fix it in http-remoting3, where we should also start appending the http-remoting version information.

On Jul 7, 2017, at 20:59, Brad Moylan <notifications@github.com<mailto:notifications@github.com>> wrote:


http-remoting currently creates user-agent strings of the format <product-name> (<product-version>), while the majority of the internet uses <product-name>/<product-version>.

Reference:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent[developer.mozilla.org]<https://urldefense.proofpoint.com/v2/url?u=https-3A__developer.mozilla.org_en-2DUS_docs_Web_HTTP_Headers_User-2DAgent&d=DwMCaQ&c=izlc9mHr637UR4lpLEZLFFS3Vn2UXBrZ4tFb6oOnmz8&r=Vp81aOxWZvuVgVK_wp-VF3pIYG92B19LcCw6XKeYC0U&m=NMZhqlOk-uxiHEP5xxtVCunkgoRkqsFUSnod5ovn_z4&s=rq5FLkW95UinykwFlogDOhcd1k7LRIV-k7w6ngmFsOw&e=>
https://en.wikipedia.org/wiki/User_agent[en.wikipedia.org]<https://urldefense.proofpoint.com/v2/url?u=https-3A__en.wikipedia.org_wiki_User-5Fagent&d=DwMCaQ&c=izlc9mHr637UR4lpLEZLFFS3Vn2UXBrZ4tFb6oOnmz8&r=Vp81aOxWZvuVgVK_wp-VF3pIYG92B19LcCw6XKeYC0U&m=NMZhqlOk-uxiHEP5xxtVCunkgoRkqsFUSnod5ovn_z4&s=jAMcGWPVOMnqxbXe3hcqVxdJUE8R0RQ4lEqctkSre18&e=>

Is there any reason for the nonstandard behavior?
