### ISSUE TITLE
fix WrappingScheduledExecutorService 

### ISSUE THREAD

**Issue by bavardage** [palantir/conjure-java-runtime#474]
I think `schedule` and `scheduleAtFixedRate` should have different behaviour w.r.t. wrapping

 - `schedule` to use trace id at submission time (current behaviour)
 - `scheduleAtFixedRate` to create a new trace each time

**Comment by iamdanfox** [comment]
For future readers, this class has been moved to https://github.com/palantir/tracing-java/blob/develop/tracing/src/main/java/com/palantir/tracing/WrappingScheduledExecutorService.java
