### ISSUE TITLE
Implement BearerTokenParamConverter that converts IAE -> ForbiddenException

### ISSUE THREAD

**Issue by gracew** [palantir/conjure-java-runtime#477]
moved from internal issue witchcraft#346

**Comment by uschi2000** [comment]
But it is an IllegalArgument, no?

**Comment by bavardage** [comment]
https://httpstatuses.com/401

> The request has not been applied because it lacks valid authentication credentials for the target resource.

Seems like 400 is more about your body..?

**Comment by bavardage** [comment]
it also helps hugely with debugging, given you very rarely get to see the auth header (it's not _safe_ to log, etc). Being able to see this show up as a 401 (someone wrote some bad python!) would have been fairly useful.

**Comment by bavardage** [comment]
I'm now reading various http specs (fun..)

![image](https://user-images.githubusercontent.com/24711/28432683-2380b0ee-6d89-11e7-8459-ff918fe865ae.png)

only use 400 if nothing else works?

**Comment by uschi2000** [comment]
OK, fair enough.
