### ISSUE TITLE
Optional HeaderParams do not work as expected

### ISSUE THREAD

**Issue by ghost** [palantir/conjure-java-runtime#483]
If I have:

```
interface FooService {
  void doFoo(@HeaderParam("On-Behalf-Of") @Safe Optional<String> onBehalfOf);
}
```

And I call it as such:

```
myFooService.doFoo(Optional.empty());
```

Then in my witchcraft my FooResource get's onBehalfOff as `Optional.of("")` instead of `Optional.empty()`.

**Comment by uschi2000** [comment]
Want to take a shot at this, Jared?

**Comment by ghost** [comment]
Will put it on my queue but no guarantee I can get to in the next 1.5 weeks

**Comment by iamdanfox** [comment]
This seems like a very similar issue to https://github.com/palantir/conjure-java-runtime/issues/384
