### ISSUE TITLE
change ClientConfigurations#of to take in SslConfiguration

### ISSUE THREAD

**Issue by gracew** [palantir/conjure-java-runtime#484]
rather than needing to specify SslSocketFactory and X509TrustManager separately.

This is on version 3.0.0-beta1. 

Thoughts @uschi2000 ? happy to submit a PR to make this change

**Comment by uschi2000** [comment]
ClientConfiguration takes JVM/in-memory objects, SslConfiguration references on disk paths.

**Comment by uschi2000** [comment]
Don't think I want to conflate these two

**Comment by gracew** [comment]
Ok, sure. This method should only be used in special cases or for tests so I suppose the extra verbosity isn't really a big deal.

(although if we're going to be purists, the `ClientConfigurations#of(ServiceConfiguration)` method also references on-disk paths via `ServiceConfiguration`).

**Comment by uschi2000** [comment]
Yes, it does. But it produces a ClientConfiguration that references in-mem things only.
