### ISSUE TITLE
CompletableFuture.join hangs if connection to server fails

### ISSUE THREAD

**Issue by meditativeape** [palantir/conjure-java-runtime#504]
Hitting a retrofit endpoint that returns a `CompletableFuture` and calling `join` will block forever if the connection to server fails (invalid URL, server not running, etc). There's an exception thrown in the OkHttp Dispatcher thread, but it's not properly caught by the call handler for `CompletableFuture`.

Repro at https://github.com/palantir/http-remoting/pull/503

**Comment by uschi2000** [comment]
@j-baker

**Comment by j-baker** [comment]
Yep, I've been talking to @meditativeape about this. See my PR to fix this.
