### ISSUE TITLE
set connection/read timeout on client

### ISSUE THREAD

**Issue by sixinli** [palantir/conjure-java-runtime#512]
Hi,

I am trying to set connection timeout on the client and realized that its not possible with `AbstractFeignJaxRsClient` https://github.com/palantir/http-remoting/blob/aafb00d031019c893c08b12b61c6511adbb44097/jaxrs-clients/src/main/java/com/palantir/remoting3/jaxrs/AbstractFeignJaxRsClientBuilder.java#L140, and request timeout doesnt seem to be working for my use case (want to check if server is down but want to lower the timeout to 1-2s)

this does not match the behavior for `Retrofit2Client` https://github.com/palantir/http-remoting/blob/04bf50f536865d4678e34ecdc3cdbf7dd8af2f6d/retrofit2-clients/src/main/java/com/palantir/remoting3/retrofit2/Retrofit2ClientBuilder.java#L100 and I wonder why that's different?

**Comment by uschi2000** [comment]
Feign overwrites some of the options, see https://github.com/palantir/http-remoting/blob/aafb00d031019c893c08b12b61c6511adbb44097/jaxrs-clients/src/main/java/com/palantir/remoting3/jaxrs/AbstractFeignJaxRsClientBuilder.java#L93 .

**Comment by sixinli** [comment]
unfortunately overwriting request options doesn't seem to work for the case: 
server1 making request (with default client 10s timeout) to server2, server2 is making feign call to server3 but server 3 is down... server1 timeout before server2 timeout even though the feign call has set connection/read timeout to 2s... 

it's possible that either the request timeout not working... or is not sufficient to kill the connection...switching to retrofit client fixes this issue

**Comment by uschi2000** [comment]
Can you provide a simple repro ad a test here?

Sent from Email+ secured by MobileIron

-------- Original Message --------

**Comment by uschi2000** [comment]
is this still an issue? closing for now, happy to re-open if there is any movement

**Comment by sixinli** [comment]
There's a workaround by using the retrofit2client and no time to setup an exact repro, fine with closing it
