### ISSUE TITLE
WebApplicationExceptionMapper no longer logs the exception

### ISSUE THREAD

**Issue by meditativeape** [palantir/conjure-java-runtime#521]
The remoting3 version of `WebApplicationExceptionMapper` does not log the exception; instead it just logs a warning that says the exception is deprecated and service exception should be used instead: https://github.com/palantir/http-remoting/blob/aafb00d031019c893c08b12b61c6511adbb44097/jersey-servers/src/main/java/com/palantir/remoting3/servers/jersey/WebApplicationExceptionMapper.java#L43

Is this an intentional change? I think logging a warning is fine, but dropping the actual exception is too aggressive of a change. This means there's no useful log for any JAX-RS exceptions, and forces projects to migrate all exceptions to service exception before they can release.

**Comment by uschi2000** [comment]
Yeah, that's an oversight. Want to make a PR?
