### ISSUE TITLE
http-remoting does not load balance requests

### ISSUE THREAD

**Issue by sjohnsonpal** [palantir/conjure-java-runtime#536]
Have noticed that http-remoting is not balancing requests across the list of nodes that is passed in. At the moment it seems it will only failover to other nodes on a failed request. 

Are there plans to make this balance requests across all nodes in the list?

**Comment by uschi2000** [comment]
It's not so obvious that this is generally the desired behavior (at least with out standard networking setups today). For example, some services cache (partial) responses internally; thus, randomizing nodes could yield cache misses on many code paths.

**Comment by uschi2000** [comment]
More abstractly, a certain notion of sticky sessions may be desired even when nodes are semantically stateless.

**Comment by uschi2000** [comment]
And yet I agree that there are other services for which per-call randomization is desired :/

**Comment by sjohnsonpal** [comment]
Yeah I think the main concern is that I want to be able to scale services horizontally and at the moment that's not quite achievable.

**Comment by uschi2000** [comment]
Different consumers will use different target URLs, but every single consumer keeps hitting the same node until it becomes unavailable. Again, there’s a tradeoff between always randomizing and allowing for a certain type of locality, and I’m not convinced we have empirically explored what this tradeoff looks like in different use-cases.

**Comment by schlosna** [comment]
Think we'll need to do some work here as in most cases we probably want even load distribution over sticky sessions for cache optimizations (and I'd posit we should push those cache optimizations down a level so they're shared, but out of scope for this issue).

@chrisalice for SA

**Comment by alicederyn** [comment]
Presumably we'd want to reuse the same node for the same user (since that's likely to increase cache hits) and randomise nodes between users (since that distributes load better) -- can we leverage the `On-Behalf-Of` work for this? (This is one of the strategies good load-balancing proxies use.)

**Comment by uschi2000** [comment]
I don't think we're going to implement this in http-remoting. More complex routing logic should be handled in the proxy mesh layer.
