### ISSUE TITLE
Handle Error Codes for non-remoting clients

### ISSUE THREAD

**Issue by kkropff** [palantir/conjure-java-runtime#56]
The exception mapper returns 500 in several situations where different error codes are more appropriate.  Occurs when using a non-remoting client to interact with the server:

<redacted>

**Comment by markelliot** [comment]
I think this is fixed as of Adam's latest commit.

**Comment by markelliot** [comment]
Er, once #45 merges.

**Comment by kkropff** [comment]
Ah, agreed, that looks like exactly this.  Closing

**Comment by TheBeruriahIncident** [comment]
There are actually two very intertwined issues here (client and server), and it sounds like your issue is the server side. Already done at https://github.com/palantir/http-remoting/pull/48. :D
