### ISSUE TITLE
Retrofit2Client throws exception "Unable to create call adapter for class java.lang.String"

### ISSUE THREAD

**Issue by sixinli** [palantir/conjure-java-runtime#561]
```
Unable to create call adapter for class java.lang.String
    for method <myService>.<myMethod> cause java.lang.IllegalArgumentException: Could not locate call adapter for class java.lang.String.
  Tried:
   * com.palantir.remoting2.retrofit2.AsyncSerializableErrorCallAdapterFactory
   * retrofit2.DefaultCallAdapterFactory stack java.lang.IllegalArgumentException: Unable to create call adapter for class java.lang.String
    for method <myService>.<myMethod>
```

where `<myService>` looks like

```
@Path("/my-method")
public interface MyService {
    @GET
    @Produces(MediaType.TEXT_PLAIN)
    String myMethod();
}
```

**Comment by iamdanfox** [comment]
@sixinli Retrofit2Client cannot use an interface annotated with jaxrs annotations like your `MyService`.  You'd need to ensure your interface has _retrofit_ annotations, e.g.:

```java
import retrofit2.Call;
import retrofit2.http.GET;

public interface MyService {
    @GET("/my-method")
    Call<String> myMethod();
}
```

**Comment by 143Deepu** [comment]
same Error comes POST Method how to rectify the error help us..........

` @FormUrlEncoded
    @POST
    Call Login(@Field("method") String method,@Field("email") String username, @Field("password") String password);
`
My Error is:

> java.lang.IllegalArgumentException: Unable to create call adapter for interface retrofit2.Call
        for method Interface.Login

**Comment by hitesh-dhamshaniya** [comment]
I am developing project using kotlin language and for me that error occurs due to did not used suspend fun in retrofit service method. After updating it, the error gone.

```
interface ProfileService {

    @Headers("Accept: application/json")
    @DELETE("logout")
    suspend fun logout(): Response<BaseEntity>
}
```

**Comment by jyotirmayg** [comment]
> I am developing project using kotlin language and for me that error occurs due to did not used suspend fun in retrofit service method. After updating it, the error gone.
> 
> ```
> interface ProfileService {
> 
>     @Headers("Accept: application/json")
>     @DELETE("logout")
>     suspend fun logout(): Response<BaseEntity>
> }
> ```

I used the suspend fun in the retrofit service method, but i am getting this error.
Can you share the retrofit dependency version?

**Comment by rohegde7** [comment]
@jyotirmayg These are my retrofit dependencies. My issue got resolved after marking the interface method as suspend.

   ```
    // Retrofit 2

    implementation 'com.squareup.retrofit2:converter-jackson:2.0.0'
    implementation 'com.jakewharton.retrofit:retrofit2-rxjava2-adapter:1.0.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.6.1'
    implementation 'com.jakewharton.rxbinding2:rxbinding:2.1.1'
    implementation 'com.squareup.retrofit2:retrofit:2.6.1'
```

**Comment by lekeCoder** [comment]
l know this has been awhile. l am seeing this error in release builds only. what could be the problem? Can you share your proguard settings?

**Comment by CharukaSilva** [comment]
> l know this has been awhile. l am seeing this error in release builds only. what could be the problem? Can you share your proguard settings?

https://github.com/square/retrofit/blob/master/retrofit/src/main/resources/META-INF/proguard/retrofit2.pro

**Comment by CharukaSilva** [comment]
> l know this has been awhile. l am seeing this error in release builds only. what could be the problem? Can you share your proguard settings?

try 

-if class *
-keepclasseswithmembers class <1> {
    <init>(...);
    @com.google.gson.annotations.SerializedName <fields>;
}

**Comment by Kanunnikoff** [comment]
> l know this has been awhile. l am seeing this error in release builds only. what could be the problem? Can you share your proguard settings?

I encountered the same problem on release builds after switching to Gradle 8 and updating the libraries. Adding [these ProGuard rules](https://github.com/square/retrofit/blob/master/retrofit/src/main/resources/META-INF/proguard/retrofit2.pro) solved the problem.
