### ISSUE TITLE
Only generate 63 bits of traceID

### ISSUE THREAD

**Issue by chewr** [palantir/conjure-java-runtime#570]
Generating random IDs for tracing currently generates an entire 64-bit long. This isn't as portable as generating 63 random bits which is agnostic of signedness

https://github.com/palantir/http-remoting/blob/develop/tracing/src/main/java/com/palantir/remoting3/tracing/Tracers.java#L35

**Comment by uschi2000** [comment]
Do you have an example of a workflow/tool that breaks due to 64 bit ids?

**Comment by chewr** [comment]
Traces propagated from request headers in the zipkin-go-opentracing library are cast between uint64 and int64. The go implementation explicitly drops the MSB from generated TraceIDs, offering transparent portability to consumers expecting signed or unsigned implementations without loss of generality. This was manifesting as inconsistent TraceIDs between go and java products within the same ecosystem at Palantir.

This could arguably be a bug in the zipkin implementation.
