### ISSUE TITLE
Tracing package should not change on major version bumps

### ISSUE THREAD

**Issue by j-baker** [palantir/conjure-java-runtime#580]
Wanted to drop this in so it's tracked for 4.0 - the class Tracer is a singleton; you register observers to get traces, and every tracer reports to the list of observers. Every time we change the package name we add a new singleton.

This means that an internal app which wants full trace coverage (through e.g. libraries like tritium-tracing) must register remoting1, remoting2 and remoting3 observers. In practice, they only register a single observer, so would miss out on events. E.g. tritium-tracing is remoting1, so is functionally useless now.

I would propose simply not changing the package name in future (or else a final move to remoting-api (it's API!) and linking the remoting3 class pointing to that) - this is a static singleton and must remain so.

**Comment by j-baker** [comment]
Or just move the tracing java lib into a separate project.

**Comment by markelliot** [comment]
prefer moving it to a separate repo

**Comment by iamdanfox** [comment]
These classes now live in http://github.com/palantir/tracing-java.  From 3.45.0 onwards, all remoting tracing classes delegate to tracing-java: https://github.com/palantir/conjure-java-runtime/pull/799
