### ISSUE TITLE
Remoting clients are not ideal for leader-aware services

### ISSUE THREAD

**Issue by nziebart** [palantir/conjure-java-runtime#585]
Leader-aware services would like a way to redirect clients to the leader and keep them there. However, a given service node will not always know the URI of the leader.

Some example scenarios would be:
(a) A node is partitioned away from the others, and cannot contact any of them to determine who the leader is
(b) A leader election is in progress, and no one is the leader
(c) A quorum of nodes is not yet available, and a leader election cannot make progress until they become available
(d) A node is a follower, and knows who the leader is

Case (d) is pretty easy; we can just issue a 308. However the other cases are not well supported by the current retry logic.

One option would be to always issue a 308 to some random node in any of the above cases. However, this is not great for (b) and (c), because it does not result in any backoff.

If we simply modify the retry logic to try a random node on 503, that would probably suffice.

**Comment by markelliot** [comment]
Perhaps we should instead make our leader aware proxy simply forward requests to the leader?

**Comment by nziebart** [comment]
That would incur an extra network hop, and in rare cases like (a) is not possible.

It would make the client side logic simpler but, in any scenario where we could reliably forward to the leader, it seems like we could also issue a 308 / redirect.

Though I guess we could just return 503 until we know who the leader is, at which point we redirect to it. Though again, it does not solve (a).

**Comment by nziebart** [comment]
Spoke with @uschi2000 offline - proposed fix is just to retry on a random node on 503
