### ISSUE TITLE
Return ServiceException with 413

### ISSUE THREAD

**Issue by jroitgrund** [palantir/conjure-java-runtime#613]
In my Jersey service, I throw `ServiceException` to benefit from the consistent logging and serialization of `com.palantir.remoting3.servers.jersey.ServiceExceptionMapper`. However, this means I am forced to use an HTTP error code from `ErrorType.Code`. In particular, I can't return a 413 when requests are too large.

**Comment by uschi2000** [comment]
This is by design: we explicitly don’t support arbitrary HTTP mechanisms (including headers and response codes).
