### ISSUE TITLE
RemotingOkHttpClient should differentiate different IOExceptions

### ISSUE THREAD

**Issue by uschi2000** [palantir/conjure-java-runtime#628]

**Comment by pkoenig10** [comment]
I think it would also be preferable to throw custom unchecked exceptions. Currently an `IOException` thrown in `RemotingOkHttpCall` is caught by Feign and wrapped, making it difficult for clients to determine what went wrong.

I think the only thing we would lose by doing this is the logging that Feign does when it catches an `IOException` (not sure if we depend on that or not). This would also be a break for any clients that currently catch `feign.RetryableException` when making calls.
