### ISSUE TITLE
Get develop into a releasable state

### ISSUE THREAD

**Issue by iamdanfox** [palantir/conjure-java-runtime#646]
3.8.1 is widely used internally and we need to pick up @ellisjoe's new PR "Limit non streaming requests to 50MB" #644.  Internal ETE tests on the data ingestion product show 3.9.0-beta2 contains regressions, I'd like to roll this back from develop and release new RCs from a `release/okhttp-refactor` branch.

I'm going to attempt to revert the following PRs and move them to the `release/okhttp-refactor` branch, with all others kept on develop:

## 3.9.0-beta3

- **[REVERT]** Fixed handling of HEAD requests (#643)
- **[REVERT]** Remove family and hostname tags from metrics (#642)
- **[KEEP]** Limit non-streaming requests to 50MB (#644)

## 3.9.0-beta2

- **[KEEP]** switch to debug logging on invalid user agents (#638)
- **[KEEP]** SerializableError can now contain sensitive UnsafeArgs as well as SafeArgs (#641)

## 3.9.0-beta1

- **[REVERT]** RemotingOkHttpCall response handlers do not leak connections (#633)
- **[REVERT]** Enable wrapping a ScheduledExecutorService with a new trace for every execution (#632)
- **[REVERT]** [BREAK] Refactor okhttp-clients: handle all custom behavior by wrapping calls in RemotingOkHttpCall (#624)

cc @uschi2000 for SA

**Comment by ellisjoe** [comment]
+1

**Comment by iamdanfox** [comment]
I've [released](https://circleci.com/gh/palantir/http-remoting/1862) 3.9.0 with the PRs labelled `[KEEP]` and re-applied all the reverted PRs to a new protected branch: **`release/okhttp-refactor`**, which we can tag as 3.10.0-beta1

**Comment by iamdanfox** [comment]
Have tagged 3.11.0-beta1 on the `release/okhttp-refactor` branch to allow us to continue trialing this stuff internally: https://github.com/palantir/http-remoting/releases/tag/3.11.0-beta1
