### ISSUE TITLE
Move UserAgent to http-remoting-api

### ISSUE THREAD

**Issue by ash211** [palantir/conjure-java-runtime#661]
@uschi2000 can you please tag this with an API break label?  When we go to remoting4 I'd like to be able to use this class in the API of our foundry-spark library.

See also https://github.com/palantir/http-remoting-api/issues/59

**Comment by iamdanfox** [comment]
This got implemented when we moved http-remoting-api -> conjure-java-runtime-api: https://github.com/palantir/conjure-java-runtime-api
