### ISSUE TITLE
Bug where completable future is never completed

### ISSUE THREAD

**Issue by carrino** [palantir/conjure-java-runtime#664]
in AsyncSerializableErrorCallAdapterFactory
SerializableErrorToExceptionConverter.getException
This method may throw a RuntimeException that is never put in the future.  This future will then hang forever. We have code that refreshes a token periodically that hangs here if the auth server is rebooted.
```
   private static String readBodyAsString(InputStream body) {
        try (Reader reader = new InputStreamReader(body, StandardCharsets.UTF_8)) {
            return CharStreams.toString(reader);
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }
```

**Comment by iamdanfox** [comment]
@carrino can you confirm what version of http-remoting you're using?

**Comment by j-baker** [comment]
So I believe that this bug existed, but I'm not convinced it has done since October/early November.

**Comment by iamdanfox** [comment]
Yeah, okhttp-clients was refactored significantly in 3.13.1... at latest http-remoting (3.14.0), it seems like the problematic method `SerializableErrorToExceptionConverter#getException` is no longer called from prod code.
