### ISSUE TITLE
Retrofit clients can't reach an endpoint with an empty path (but jax-rs can)

### ISSUE THREAD

**Issue by iamdanfox** [palantir/conjure-java-runtime#673]
## Repro:

1. Set up a server with some context-path e.g. `https://host/context-path`
1. Expose a jax-rs service annotated with `@Path("/")` with a single endpoint e.g. `myEndpoint`
1. Construct a `Retrofit2Client` to connect to `https://host/context-path` and pass in a `FooServiceRetrofit` interface with an endpoint annotated with `retrofit2.http.GET`.

## Expected:

- Calling the client endpoint should connect to the server and return a sensible value.  Note: this works fine with a feign `JaxRsClient`!

## Actual (option 1):

If the endpoint is annotated `@GET("")`, then you get an exception when you try to call it:

```
java.lang.IllegalArgumentException: Missing either @GET URL or @Url parameter.
    for method FooServiceRetrofit.myEndpoint
	at retrofit2.ServiceMethod$Builder.methodError(ServiceMethod.java:752)
	at retrofit2.ServiceMethod$Builder.methodError(ServiceMethod.java:743)
	at retrofit2.ServiceMethod$Builder.build(ServiceMethod.java:208)
	at retrofit2.Retrofit.loadServiceMethod(Retrofit.java:170)
	at retrofit2.Retrofit$1.invoke(Retrofit.java:147)
	at com.sun.proxy.$Proxy67.myEndpoint(Unknown Source)
```

## Actual (option 2):

If the endpoint is annotated `@GET("/")` then the client will forget about the context path and try to connect to the root (`https://host`):

```
java.io.IOException: Error 404. (Failed to parse response body as SerializableError.) Body:
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 404 Not Found</title>
</head>
<body><h2>HTTP ERROR 404</h2>
<p>Problem accessing /. Reason:
<pre>    Not Found</pre></p><hr><a href="http://eclipse.org/jetty">Powered by Jetty:// 9.4.8.v20171121</a><hr/>

</body>
</html>
```

Not sure whether this is fixable in http-remoting or whether we need to push something upstream to retrofit here :/

**Comment by markelliot** [comment]
what about `./` as a value?

**Comment by markelliot** [comment]
or alternative we need to be setting `baseUrl` in our Retrofit clients and putting the context path there

**Comment by iamdanfox** [comment]
Bam looks like `@GET("./")` works perfectly!  Looks like this is an easy close :)
