### ISSUE TITLE
Better client failover and distribution amongst URIs

### ISSUE THREAD

**Issue by gregakinman** [palantir/conjure-java-runtime#678]
Writing this up to follow up about some internal conversations we had based on some internal issues we've been hitting.

Situation:

2 nodes of a service exist, and a large number of jaxrs clients exist configured with these 2 nodes' URIs. We're running into more than one instance right now where 1 node is pinned and receives almost all of the traffic and may or may not be dropping requests as a result. Configuring this node to respond with 503 upon a critical load threshold is good for QoS. However, currently, clients that receive 503 will always retry the request to the same node. This results in the node continuing to be pinned, since the rate of new request demand (i.e., how many requests the set of clients wish to issue over each unit of time) is constant, and it results in some of the clients ultimately failing after retrying. There are simply not enough resources on the first node to serve all of the requests of the clients communicating with it.

There are 2 problems with this scenario:

1) Too many clients are going for one node initially. The resolution in https://github.com/palantir/http-remoting/issues/536 seems to be correct, since at the individual request level, due to desiring sticky sessions that take advantage of server-side caching, random dispatching of requests to URIs doesn't seem desirable. However, it _is_ desirable to _begin_ each session with a random URI. And, it appears that this should happen in theory, since when a new jaxrs client is created, the order of the supplied URIs is shuffled. But we're not seeing this in practice. Further to this, perhaps something like https://github.com/palantir/http-remoting/issues/250 could help.

2) Upon receiving 503, each client only retries on the node that served it 503. Why not, after backing off for the configured time period, dispatch the next request to a random URI? Seems reasonable to try a different host if one of them is claiming to be overloaded. In situations where all clients are http-remoting jaxrs clients and all of them are receiving the same response from the same host and all of them are employing the same logic...we probably don't want this, because it results in the status quo being maintained. We want to pick another random URI, and if it's 200 OK, start sticking with it.

Even if we don't get 1) - if all clients start at the same URI, after some time, we might expect some of them to get QoS'd, in which case they'd properly fail over and begin "sessions" on other nodes of the service and better distribute the load.

cc @uschi2000 @samrogerson

**Comment by uschi2000** [comment]
Can you add a test to demonstrate the expected behavior?

Sent from Email+ secured by MobileIron

-------- Original Message --------

**Comment by gregakinman** [comment]
sure

**Comment by gregakinman** [comment]
@uschi2000 - PR with test added to show expected behavior here: https://github.com/palantir/http-remoting/pull/682. Specifically directed at 2) above.
