### ISSUE TITLE
Consider implementing OkHttpClient#newBuilder to return a RemotingOkHttpClient.Builder

### ISSUE THREAD

**Issue by gatesn** [palantir/conjure-java-runtime#688]
We've hit several cases where we want to make use of remoting's QOS, URI fallbacks/retries and other features but we haven't been able to because we need to enable a couple of extra things in OkHttp.

In this case, we want to add a cache to the OkHttpClient. Given the RemotingOkHttpClient extends the OkHttpClient, could we override the `OkHttpClient#newBuilder` method to return a RemotingOkHttpClient.Builder class that we could add functionality to but the `build` method on this builder returns a RemotingOkHttpClient?

Happy to make a PR if you think this is reasonable.

**Comment by gatesn** [comment]
Seems like this would require OkHttpClient.Builder to not be final

**Comment by uschi2000** [comment]
Mid-term, I'd like to reduce/remove functionality from http-remoting, in particular around failover and QoS handling. We've pushing that into the service mesh. So I'm a little reluctant to open up the configuration space of remoting clients.
