### ISSUE TITLE
Expose a way to reuse connection pools when ClientConfig matches

### ISSUE THREAD

**Issue by carterkozak** [palantir/conjure-java-runtime#691]
I have a service which exposes many interfaces. Without reimplementing http-remoting components myself there is no way to share my connection pool between clients communicating with the same service.

**Comment by carterkozak** [comment]
bad robot

**Comment by iamdanfox** [comment]
It seems that OkHttpClients uses a single static `okhttp3.ConnectionPool` for all requests: https://github.com/palantir/conjure-java-runtime/blob/4.5.1/okhttp-clients/src/main/java/com/palantir/conjure/java/okhttp/OkHttpClients.java#L78


Are there other connection pools somewhere that aren't being re-used?

**Comment by carterkozak** [comment]
Didn't realize that, thanks!

**Comment by j-baker** [comment]
Yeah, but it's also goofy because it means that connections to the same host with different connection settings get shared? Like it doesn't obviously seem like correct behaviour?
