### ISSUE TITLE
Make it easier to compose encoders/decoders

### ISSUE THREAD

**Issue by nmiyake** [palantir/conjure-java-runtime#70]
Currently, the encoders/decoders provided by http-remoting need to be manually nested, leading to ugly code like the following:

```
...
new QueryMapEncoder(new JacksonEncoder(ObjectMappers.guavaJdk7())),
new OptionalAwareDecoder(new TextDelegateDecoder(new JacksonDecoder(ObjectMappers.guavaJdk7()))),
...
```

Possible approaches would be to have a method that takes in a collection of delegating encoders/decoders and have it chain them directly or to use some kind of "handler" pattern.

**Comment by markelliot** [comment]
this is Feign-centric, think the ship has sailed on fixing this so going to close. Re-open if you feel strongly.
