### ISSUE TITLE
Safe log http error code and the fact that the body couldn't be parsed

### ISSUE THREAD

**Issue by justinuang** [palantir/conjure-java-runtime#702]
https://github.com/palantir/http-remoting/blob/b9160d299b5d9859090864d0b63b7c41b6864c1e/okhttp-clients/src/main/java/com/palantir/remoting3/okhttp/IoExceptionResponseHandler.java

**Comment by justinuang** [comment]
@onursatici

**Comment by iamdanfox** [comment]
This should be very achievable by switching to use [`SafeIllegalStateException`](https://github.com/palantir/safe-logging/blob/1.2.0/preconditions/src/main/java/com/palantir/logsafe/exceptions/SafeIllegalStateException.java) etc from `com.palantir.safe-logging:preconditions`

**Comment by yifeih** [comment]
@iamdanfox should I be creating a new `SafeIOException` inside of safe-logging first instead of extending the current Safe Exceptions here? https://github.com/palantir/safe-logging/tree/1.2.0/preconditions/src/main/java/com/palantir/logsafe/exceptions

**Comment by yifeih** [comment]
@iamdanfox should I be creating a `SafeIOException` inside of safe-logging:preconditions first and then using that in http-remoting?

**Comment by iamdanfox** [comment]
@yifeih that sounds like a good plan, it's nice to have one canonical place for these to save people re-inventing the wheel!
