### ISSUE TITLE
Fail fast when trying to use Resource classes in `JaxRsClient.create(...)`

### ISSUE THREAD

**Issue by f-doot** [palantir/conjure-java-runtime#800]
## What happened?

I was trying to create a client for a jaxrs annotated resource by using `JaxRsClient.create(ConfirmationResource.class, USER_AGENT, CLIENT_CONFIG)`, in order to be used in a docker-based test. The resource looked like this:

```java
@Consumes(MediaType.APPLICATION_JSON)
@Path("/")
@Singleton
public class ConfirmationResource {
    private final Delegate delegate;

    @Inject
    public ConfirmationResource(Delegate delegate) {
        this.delegate = delegate;
    }

    @GET
    @Path("confirmCreation/{uuid}")
    public void confirmCreation(@PathParam("uuid") UUID uuid) {
        delegate.confirmCreation(uuid);
    }

    @GET
    @Path("confirmDeletion/{uuid}")
    public void confirmDeletion(@PathParam("uuid") UUID uuid) {
        delegate.confirmDeletion(uuid);
    }
}
```
This didn't work and "hung" silently along the way, in the test setup.

Extracting this to an interface and creating the JaxRsClient with the Service fixed this issue: `JaxRsClient.create(ConfirmationService.class, USER_AGENT, CLIENT_CONFIG)`

```java
@Consumes(MediaType.APPLICATION_JSON)
@Path("/")
public interface ConfirmationService {
    @GET
    @Path("confirmCreation/{uuid}")
    void confirmCreation(@PathParam("uuid") UUID uuid);

    @GET
    @Path("confirmDeletion/{uuid}")
    void void confirmDeletion(@PathParam("uuid") UUID uuid);
}
```

## What did you want to happen?

While I'm on board with this behaviour in general, I was wondering if it'd be possible for this to throw some descriptive exceptions, rather then just silently "hang". As best I could tell it failed somewhere in [this method](https://github.com/palantir/http-remoting/blob/develop/jaxrs-clients/src/main/java/com/palantir/remoting3/jaxrs/AbstractFeignJaxRsClientBuilder.java#L95), using the debugger with this was very wonky for some reason.

**Comment by iamdanfox** [comment]
What about if we added a line that verified the first argument (`ConfigurationResource.class`) is actually a Java interface, and fail fast otherwise?

**Comment by f-doot** [comment]
I think that'd be ideal here, if that's the behaviour we want to enforce.
