### ISSUE TITLE
grab new feign version that uses okhttp 2.7.5

### ISSUE THREAD

**Issue by jmcampanini** [palantir/conjure-java-runtime#83]
PR here: https://github.com/Netflix/feign/pull/356

see for details: https://corner.squareup.com/2016/03/certificate-pinner-vulnerability.html

**Comment by a-k-g** [comment]
It seems like this issue can now be closed. We seem to be using feign 8.17 which actually gets okhttp 3.2. https://github.com/Netflix/feign/blob/v8.17.0/okhttp/build.gradle
