### ISSUE TITLE
Deserializing aliases that are optionals throws exception

### ISSUE THREAD

**Issue by abless** [palantir/conjure-java-runtime#851]
## What happened?

Consider:

	MyAlias:
	  alias: optional<OffsetDateTime>
			  
	MyObject:
	  fields:
	    token:
	      type: MyAlias

If `MyObject.token` is an `Optional#empty`, then serialization will serialize token to "null" and deserialization will throw an exception (token cannot be null).

## What did you want to happen?

Deserialization should work as expected.

This seems to be an issue for aliases. If I don't use an alias (and instead encode the `optional<OffsetDateTime>` directly) things work as expected.

**Comment by j-baker** [comment]
Let’s keep this open

**Comment by maciekf** [comment]
I also run into the issue with a union:
```
MyAlias:
  alias: optional<any>

MyUnion:
  union:
    option1: MyAlias
```

**Comment by fsamuel-bs** [comment]
https://github.com/FasterXML/jackson-databind/issues/2943 - think this is ultimately a Jackson issue, but will implement https://github.com/palantir/conjure-java/pull/170 in the meantime.

**Comment by carterkozak** [comment]
I had thought this was resolved, is it still an issue on the latest conjure release?

**Comment by carterkozak** [comment]
Ah you're right, this is broken. Fortunately we can fix it with a generator change.

**Comment by carterkozak** [comment]
https://github.com/palantir/conjure-java/pull/1166

**Comment by carterkozak** [comment]
Fixed using the latest generator release.
