### ISSUE TITLE
Misleading comments in test ignores

### ISSUE THREAD

**Issue by dansanduleac** [palantir/conjure-java-runtime#918]
These comments are incorrect:

https://github.com/palantir/conjure-java-runtime/blob/6ec9ce5aceaad6a111aad468c0dc4096811f25f1/conjure-java-client-verifier/src/test/resources/ignored-test-cases.yml#L5-L6

We are already on jackson 2.9 and already disable `ALLOW_COERCION_OF_SCALARS`, but these coersions are still allowed, unfortunately.

**Comment by dansanduleac** [comment]
Ok so digging into this, there is a bug where afterburner ignores `ALLOW_COERCION_OF_SCALARS`, so since we use afterburner, this flag made no difference.
PR up to fix it: https://github.com/FasterXML/jackson-modules-base/pull/70

**Comment by iamdanfox** [comment]
File no longer contains these comments.

https://github.com/palantir/conjure-java-runtime/blob/a64984e88b8d71626b7c64e291ad55dce03bfc7c/conjure-java-client-verifier/src/test/resources/ignored-test-cases.yml
