### ISSUE TITLE
Conjure OkHttp client hangs indefinitely if an interceptor throws

### ISSUE THREAD

**Issue by carterkozak** [palantir/conjure-java-runtime#925]
## What happened?

Conjure OkHttp client hangs indefinitely if an interceptor throws.

## What did you want to happen?

The exception should terminate the call and ideally propagate the failure in some way.

**Comment by iamdanfox** [comment]
I think we've come up against this before - it's just a quirk of okhttp that if anything in the `RealInterceptorChain` throws a non-IOException, then it blasts out of the `execute` method without notifying `eventListener.callFailed`.

https://github.com/square/okhttp/blob/parent-3.12.0/okhttp/src/main/java/okhttp3/RealCall.java#L90-L95

This is why we have the weird `IoRemoteException` thing to propagate `RemoteExceptions` (which are just runtime exceptions).

Given that we control the okhttp client construction, maybe we should defensively wrap all the interceptors in catch blocks that rethrow IOExceptions?

**Comment by j-baker** [comment]
or add our own interceptor that rethrows IOExceptions?

**Comment by carterkozak** [comment]
fix is #1125
