### ISSUE TITLE
Round robin selection strategy will advance URL selector twice on retry

### ISSUE THREAD

**Issue by pkoenig10** [palantir/conjure-java-runtime#942]
## What happened?

When a failure happens in a client using the round robin node selection strategy, the URL is advanced twice.

The first time will happen in the request callback, either in the [failure handler](https://github.com/palantir/conjure-java-runtime/blob/4.14.0/okhttp-clients/src/main/java/com/palantir/conjure/java/okhttp/RemotingOkHttpCall.java#L182) or the [QoS unavailable handler](https://github.com/palantir/conjure-java-runtime/blob/4.14.0/okhttp-clients/src/main/java/com/palantir/conjure/java/okhttp/RemotingOkHttpCall.java#L308).

The second time will happen [in the round robin interceptor](
https://github.com/palantir/conjure-java-runtime/blob/4.14.0/okhttp-clients/src/main/java/com/palantir/conjure/java/okhttp/RoundRobinUrlInterceptor.java#L44) for the retried request.

If the number of urls is odd then this behavior is acceptable. However if the number of urls is even then we may try a second time on some hosts before we've tried once on other hosts.

## What did you want to happen?

When retrying a request with a round robin selection strategy we should only advance the URL selector once.

**Comment by hsaraogi** [comment]
Can we please prioritize this, this has caused failing builds: https://support-jira.palantir.tech/browse/PDS-82290.

**Comment by pkoenig10** [comment]
Fixed in #960
