### ISSUE TITLE
Afterburner compatibility on JDK9+

### ISSUE THREAD

**Issue by markelliot** [palantir/conjure-java-runtime#964]
## What happened?

Afterburner performs what JDK9+ considers illegal reflective access, and, as a result, generates some warnings on newer JVMs.

## What did you want to happen?

Eliminate the warnings. Relevant discussion for how here: https://github.com/FasterXML/jackson-modules-base/issues/37#issuecomment-414137656

**Comment by carterkozak** [comment]
Do we have any benchmarks showing a performance improvement using afterburner? I've been unable to find anything published, or produce numbers myself showing an improvement.

**Comment by markelliot** [comment]
@schlosna originally recommended its inclusion. Some benchmarks that show benefit for smaller docs here: https://github.com/fabienrenaud/java-json-benchmark

**Comment by markelliot** [comment]
But...please open a different issue if you want to investigate removing afterburner. There's a relatively small fix proposed here which at least stops production of warnings on new JVMs.

**Comment by schlosna** [comment]
I don’t think we have any Open JMH benchmarks yet for Conjure+Jackson +/- Afterburner, but it would be useful. I’d be interested in results with/without Afterburner on OpenJDK 8 & 11.

**Comment by iamdanfox** [comment]
A new development (as of 29th march) is a whole new implementation called [jackson-blackbird](https://github.com/stevenschlansker/jackson-blackbird)... might be worth trying out??

**Comment by iamdanfox** [comment]
I've taken a stab at just adding that one liner here: https://github.com/palantir/conjure-java-runtime/pull/2021.
