### ISSUE TITLE
Allow trustStorePassword to be configured in SslConfiguration

### ISSUE THREAD

**Issue by leeavital** [palantir/conjure-java-runtime#97]

**Comment by markelliot** [comment]
Why is a trustStorePassword required? JKS files, for instance, do not require passwords to read the trusted certificates.

**Comment by nmiyake** [comment]
Out of curiosity, what is the use case for this? Trust store certificate entries can be read without a password, so the only use for a password is integrity checking.

**Comment by leeavital** [comment]
False alarm -- someone was trying to fill in a trust store password but wound up omitting it. Closing this out.

**Comment by philcchen** [comment]
(tagging @nmiyake )

Unsure if this is a valid use case for having the trustStorePassword in SslConfiguration, but it appears to be a requirement for the Kafka Client Api (https://kafka.apache.org/documentation.html#security_configclients). Haven't dug too deep into why Kafka needs the trustStorePassword, but it appears they do validate that the password is correct.

I've worked around this in my local configuration by explicitly passing in the trustStorePassword.
