### ISSUE TITLE
CollectionValidationModule interacts poorly with ObjectMapper.convertValue

### ISSUE THREAD

**Issue by dtobin** [palantir/conjure-java-runtime#995]
## What happened?

`CollectionValidationModule` was added to the client and server ObjectMappers in 4.17.0. It is intended to catch null values in collections, but it also fails if you try to convert an object with optional fields:

```
    @JsonDeserialize(as = ImmutableFoo.class)
    @JsonSerialize(as = ImmutableFoo.class)
    @Value.Immutable
    interface Foo {
        String value();
        Optional<String> optionalValue();
    }

    @Test
    public void testMapper() {
        Foo foo = ImmutableFoo.builder().value("a").build();
        ObjectMapper mapper = com.palantir.conjure.java.serialization.ObjectMappers.newServerObjectMapper();
        mapper.convertValue(foo, new TypeReference<Map<String, Object>>(){}); // this fails
    }
```

I believe that if we're going to check for null values, the published ObjectMappers should also set `.setSerializationInclusion(JsonInclude.Include.NON_NULL)` so that they don't produce the null values in the first place.

Currently this only breaks tests because `CollectionValidationModule` uses an assert, but if we're going to check for this in tests, it should be because we want the check to always pass in production code as well.

## What did you want to happen?

`mapper.convertValue` should succeed because it doesn't produce null values.

**Comment by carterkozak** [comment]
Flagging that setting `.setSerializationInclusion(JsonInclude.Include.NON_NULL)` on the conjure object mapper would break typescript clients.

**Comment by ferozco** [comment]
@cakofony `.setSerializationInclusion(JsonInclude.Include.NON_NULL)` wouldn't break TypeScript consumers since for any optional field the generated typings are `T | null | undefined`.

**Comment by carterkozak** [comment]
Oh wonderful, I stand corrected

**Comment by carterkozak** [comment]
This change should resolve the issue in this ticket: https://github.com/palantir/conjure-java-runtime/pull/996

**Comment by carterkozak** [comment]
Released https://github.com/palantir/conjure-java-runtime/releases/tag/4.17.2

**Comment by dtobin** [comment]
Thanks for the quick turnaround!
